// Glossário: [termo, definição (HTML), [IDs das disciplinas onde o termo é explicado]].
// As definições resumem o conteúdo das disciplinas; as fontes estão nas referências de cada uma.
(function(){
  const D = {
    lider: "f1-o-lider-de-times-tech", creative: "f1-it-creative-strategy", produto: "f1-estrategia-de-produtos-digitais", lean: "f1-lean-startup",
    equipes: "f2-montando-equipes-de-alta-performance", ageis: "f2-gestao-de-times-ageis-e-multidisciplinares", fin: "f2-gestao-financeira-e-sourcing", com: "f2-comunicacao-e-negociacao-em-projetos-de-ti",
    ea: "f3-ea-enterprise-architecture", direito: "f3-direito-digital", privacy: "f3-privacy-by-design-e-by-default", dev: "f3-gestao-de-desenvolvimento-de-software",
    arq: "f4-arquiteturas-de-software", gov: "f4-governanca-de-tecnologia", integ: "f4-integracoes-de-plataforma-e-ecossistemas", ds: "f4-data-science-ia", devops: "f4-devops-cyber-security",
    cloud: "f5-estrategia-cloud-finops", retencao: "f5-gestao-das-equipes-e-retencao", obs: "f5-observability", cultura: "f5-cultura-organizacional", mudanca: "f5-gestao-da-mudanca-em-ti", adv: "f5-advanced-leadership-skills"
  };
  window.GLOSSARIO = [
    ["7 Rs", "Estratégias de migração para a nuvem (AWS): Retire, Retain, Rehost, Relocate, Replatform, Repurchase e Refactor.", [D.cloud]],
    ["ADKAR", "Modelo da Prosci para mudança no nível individual: Awareness, Desire, Knowledge, Ability, Reinforcement. O primeiro elemento com nota baixa é o ponto de bloqueio.", [D.mudanca]],
    ["ADR", "Architecture Decision Record: registro curto de uma decisão de arquitetura, com contexto, decisão, status e consequências (Michael Nygard).", [D.mudanca, D.ea]],
    ["Advice process", "Qualquer pessoa pode tomar uma decisão de arquitetura, desde que antes consulte os afetados e os especialistas e registre a decisão.", [D.ea]],
    ["AI Act", "Regulamento europeu de IA (UE 2024/1689), baseado em risco: proibido, alto risco, transparência e mínimo. Prazos alterados pelo Digital Omnibus de 2026; confira a situação atual.", [D.direito]],
    ["ANPD", "Autoridade brasileira que fiscaliza a LGPD e, desde 2026, também o ECA Digital.", [D.privacy, D.direito]],
    ["ArchiMate", "Linguagem de modelagem de arquitetura corporativa do The Open Group, com camadas de estratégia, negócio, aplicação e tecnologia.", [D.arq]],
    ["Art. 19 do Marco Civil", "Regra sobre a responsabilidade das plataformas por conteúdo de terceiros. Declarado parcialmente inconstitucional pelo STF em 26/06/2025; em regra, vale agora a notificação extrajudicial.", [D.direito]],
    ["BATNA", "Best Alternative To a Negotiated Agreement: a melhor alternativa se não houver acordo. Define o poder de negociação.", [D.com]],
    ["Bimodal IT", "Modelo do Gartner (2014) que separa a TI em modo 1 (estável, eficiente) e modo 2 (exploratório, ágil). Evoluiu para o Techquilibrium.", [D.fin]],
    ["Bounded Context", "Fronteira explícita dentro da qual um modelo de domínio e sua linguagem ubíqua são consistentes (DDD).", [D.dev]],
    ["BSC (Balanced Scorecard)", "Kaplan e Norton: traduz a estratégia em indicadores em quatro perspectivas: financeira, clientes, processos internos e aprendizado e crescimento.", [D.retencao]],
    ["Burn rate", "Velocidade de consumo do error budget. Burn rate 1 gasta exatamente o orçamento no período do SLO.", [D.obs]],
    ["Burnout", "Na CID-11 (OMS), resultado do estresse crônico no trabalho não gerenciado: exaustão, distanciamento ou cinismo e redução da eficácia profissional.", [D.adv]],
    ["C4 Model", "Modelo de Simon Brown para diagramar software em quatro níveis: contexto, contêineres, componentes e código. Provável sentido de \"V4 Model\" na ementa.", [D.arq]],
    ["CAC", "Custo de aquisição de cliente. Comparado ao LTV para avaliar se o crescimento é saudável.", [D.lean]],
    ["CALMS", "Resumo da cultura DevOps: Culture, Automation, Lean, Measurement, Sharing.", [D.devops]],
    ["CAPEX e OPEX", "CAPEX é investimento que vira ativo e é depreciado ou amortizado; OPEX é despesa operacional do período.", [D.fin]],
    ["CFRs", "Conversas, Feedback e Reconhecimento contínuos, que John Doerr propõe junto com os OKRs.", [D.retencao]],
    ["Chargeback e showback", "Showback mostra a cada área quanto ela consome de TI; chargeback cobra esse valor do orçamento dela.", [D.fin, D.cloud]],
    ["Clean Architecture", "Robert C. Martin: camadas concêntricas em que as dependências apontam sempre para o domínio.", [D.arq]],
    ["CNV", "Comunicação Não-Violenta (Marshall Rosenberg): observação, sentimento, necessidade e pedido.", [D.com]],
    ["COBIT", "Framework da ISACA de governança e gestão de TI. A versão 2019 tem 40 objetivos em 5 domínios: EDM, APO, BAI, DSS e MEA.", [D.gov]],
    ["Core Web Vitals", "Métricas do Google para a experiência real no navegador: LCP (até 2,5 s), INP (até 200 ms) e CLS (até 0,1).", [D.obs]],
    ["Cost of Delay", "Quanto valor se perde por esperar. Base do WSJF.", [D.ageis]],
    ["Cynefin", "Modelo de Dave Snowden com domínios claro, complicado, complexo e caótico, cada um pedindo uma forma de agir.", [D.mudanca]],
    ["Data contract", "Acordo entre produtor e consumidores de um dataset: dono, schema, SLA de atualização, regras de qualidade e política de versão.", [D.ds]],
    ["Data Mesh", "Zhamak Dehghani: propriedade por domínio, dados como produto, plataforma self-service e governança federada computacional.", [D.ds]],
    ["Delegation Poker", "Prática do Management 3.0 com sete níveis de delegação, de \"contar\" a \"delegar\".", [D.lider, D.retencao]],
    ["DevSecOps", "Segurança integrada em todo o ciclo de desenvolvimento (shift left): SAST, SCA, DAST, varredura de segredos e threat modeling.", [D.devops]],
    ["DORA (métricas)", "Frequência de deploy, lead time para mudanças, taxa de falha em mudanças e tempo de recuperação.", [D.ageis, D.devops]],
    ["Double Diamond", "Design Council: descobrir e definir (o problema), desenvolver e entregar (a solução).", [D.creative]],
    ["Drex", "Projeto do Banco Central de infraestrutura para ativos tokenizados. A primeira entrega (2026) não usa blockchain; confira a situação atual.", [D.integ]],
    ["ECA Digital", "Lei 15.211/2025, em vigor desde 17/03/2026: obrigações para produtos digitais voltados a crianças e adolescentes ou com acesso provável por eles.", [D.direito]],
    ["Error budget", "Margem de falha permitida pelo SLO. Enquanto há orçamento, o time lança; quando acaba, prioriza a confiabilidade.", [D.obs, D.devops]],
    ["Event Storming", "Workshop de Alberto Brandolini para mapear o domínio com eventos, comandos, atores e políticas na linha do tempo.", [D.dev]],
    ["Feature flag", "Chave que liga ou desliga uma funcionalidade sem novo deploy. Separa deploy de release.", [D.produto]],
    ["FinOps", "Prática que dá responsabilidade financeira ao uso variável da nuvem. Fases: informar, otimizar e operar.", [D.cloud]],
    ["Fitness function", "Teste automatizado que falha quando a arquitetura se afasta do combinado.", [D.ea]],
    ["FOCUS", "Especificação aberta da FinOps Foundation que padroniza os dados de cobrança de nuvem, SaaS e IA.", [D.cloud]],
    ["GitOps", "Estado desejado declarativo, versionado no Git, puxado automaticamente e reconciliado continuamente.", [D.dev]],
    ["Golden path", "Caminho padrão e fácil para criar e operar um serviço, oferecido pela plataforma interna.", [D.dev, D.ea]],
    ["HEART", "Framework do Google para métricas de experiência: Happiness, Engagement, Adoption, Retention, Task success.", [D.obs]],
    ["Hexagonal (Ports & Adapters)", "Alistair Cockburn: a lógica de negócio fala com o mundo por portas (interfaces) implementadas por adaptadores.", [D.arq, D.dev]],
    ["Hub-and-spoke", "Modelo operacional de dados com um time central de plataforma e governança e analistas nos times de negócio.", [D.ds]],
    ["Hype Cycle", "Modelo do Gartner: gatilho, pico das expectativas, vale da desilusão, rampa de consolidação e platô de produtividade.", [D.integ]],
    ["INVEST", "Critérios de uma boa história: Independente, Negociável, Valiosa, Estimável, Pequena, Testável.", [D.ageis]],
    ["ISO/IEC 27001 e 27002", "A 27001 traz os requisitos certificáveis de um SGSI; a 27002 é o guia dos controles (93 na versão 2022).", [D.direito]],
    ["IT4IT", "Padrão do The Open Group para gerir a TI como negócio. Quatro fluxos de valor na versão 2.1 e sete na 3.0. A ementa escreve \"IT41T\".", [D.fin]],
    ["k-anonimato", "Generalizar os quase-identificadores até que cada combinação apareça em pelo menos k registros.", [D.privacy]],
    ["Kanban", "Método de fluxo contínuo: visualizar o trabalho, limitar o WIP e melhorar o fluxo.", [D.ageis]],
    ["Kotter (8 passos)", "Urgência, coalizão, visão, comunicação, remover obstáculos, vitórias rápidas, consolidar e ancorar na cultura.", [D.mudanca]],
    ["Lakehouse", "Arquitetura que une o data lake e o data warehouse com formatos abertos (Delta Lake, Iceberg).", [D.ds]],
    ["Lean Canvas", "Ash Maurya: problema, segmento, proposta única de valor, solução, canais, receitas, custos, métricas e vantagem injusta.", [D.lean]],
    ["LeSS e SAFe", "Frameworks de agilidade em escala: o LeSS é minimalista (um backlog para vários times); o SAFe é prescritivo (trens, PI Planning).", [D.equipes]],
    ["Lei de Conway", "Organizações produzem sistemas que copiam suas estruturas de comunicação.", [D.equipes]],
    ["Lei de Little", "Tempo médio no sistema = WIP médio ÷ throughput médio.", [D.ageis]],
    ["LGPD", "Lei 13.709/2018, que regula o tratamento de dados pessoais no Brasil.", [D.privacy]],
    ["Liderança Situacional", "Hersey e Blanchard: dirigir, treinar, apoiar ou delegar conforme a competência e o comprometimento da pessoa em cada tarefa.", [D.lider]],
    ["Linguagem ubíqua", "Vocabulário comum entre negócio e time, usado na conversa e no código dentro de um bounded context.", [D.dev]],
    ["LTV", "Lifetime value: margem que um cliente gera durante a relação. Simplificado: receita mensal × margem ÷ churn mensal.", [D.lean]],
    ["MCP", "Model Context Protocol: padrão aberto para conectar aplicações de IA a ferramentas e fontes de dados.", [D.integ]],
    ["Medallion", "Camadas de dados bronze (bruto), prata (limpo e integrado) e ouro (pronto para consumo).", [D.ds]],
    ["MITRE ATT&CK", "Base pública de táticas e técnicas de adversários, usada por red, blue e purple teams.", [D.devops]],
    ["MLOps", "Práticas para versionar, treinar, implantar e monitorar modelos de ML de forma contínua.", [D.ds]],
    ["Modelo das Três Linhas", "IIA: gestão operacional (1ª linha), funções de risco e compliance (2ª) e auditoria interna (3ª).", [D.gov]],
    ["Monolito distribuído", "Serviços que compartilham banco ou precisam ser implantados juntos: a complexidade da rede sem a independência.", [D.arq]],
    ["Monolito modular", "Um único deploy organizado em módulos por domínio, com fronteiras claras. Ponto de partida recomendado (\"Monolith First\").", [D.arq]],
    ["MTTD e MTTR", "Tempo médio para detectar e para recuperar (ou responder a) um incidente. Médias podem enganar; prefira percentis.", [D.devops, D.obs]],
    ["MVP", "A menor coisa que gera aprendizado validado; não precisa ser um produto (landing page, concierge, protótipo).", [D.lean]],
    ["North Star Metric", "Métrica única que representa o valor entregue ao cliente e antecipa o crescimento do negócio.", [D.produto]],
    ["NPS", "Net Promoter Score: % de promotores (9–10) − % de detratores (0–6), de −100 a +100.", [D.creative]],
    ["OKR", "Objetivo qualitativo com 2 a 5 resultados-chave mensuráveis, em ciclos curtos (Grove, Doerr).", [D.retencao]],
    ["Open Finance", "Compartilhamento de dados e serviços financeiros entre instituições, com consentimento do cliente, via APIs padronizadas pelo Banco Central.", [D.integ]],
    ["OpenTelemetry", "Padrão aberto da CNCF para instrumentar e coletar métricas, logs e traces sem depender de fornecedor.", [D.obs]],
    ["Opportunity Solution Tree", "Teresa Torres: outcome → oportunidades → soluções → experimentos.", [D.produto]],
    ["Pivot", "Mudança estruturada de rota que preserva o que já foi aprendido.", [D.lean]],
    ["Post-mortem sem culpa", "Análise de incidente com linha do tempo, impacto, causas contribuintes e ações, focada no sistema e não em culpados.", [D.devops, D.mudanca]],
    ["Privacy by Design", "Ann Cavoukian: privacidade embutida no design e ativada por padrão (by default). Previsto no art. 46 da LGPD e no art. 25 do GDPR.", [D.privacy]],
    ["Prompt injection", "Conteúdo processado por um modelo de IA que contém instruções que ele passa a seguir.", [D.integ]],
    ["Pseudonimização", "Troca de identificadores que pode ser revertida com informação guardada à parte. O dado continua sendo pessoal.", [D.privacy]],
    ["Purple Team", "Colaboração estruturada entre red team (ataque) e blue team (defesa) para melhorar a detecção.", [D.devops]],
    ["Radical Candor", "Kim Scott: importar-se pessoalmente e desafiar diretamente. Os outros quadrantes são agressividade ofensiva, empatia ruinosa e falsidade manipuladora.", [D.retencao]],
    ["RAG", "Retrieval-Augmented Generation: buscar trechos relevantes numa base própria e passá-los ao modelo antes de gerar a resposta.", [D.integ]],
    ["RED e USE", "Métodos para escolher sinais de monitoramento: RED (Rate, Errors, Duration) para serviços; USE (Utilization, Saturation, Errors) para recursos.", [D.obs]],
    ["RFC", "Request for Comments: documento que propõe uma mudança técnica e pede opiniões antes da decisão.", [D.mudanca]],
    ["RFP", "Request for Proposal: documento formal para pedir propostas a fornecedores.", [D.fin]],
    ["Rightsizing", "Ajustar o tamanho dos recursos de nuvem ao uso real. Deve vir antes de comprar reservas.", [D.cloud]],
    ["RIPD", "Relatório de Impacto à Proteção de Dados Pessoais: documenta tratamentos de risco e as medidas de mitigação.", [D.privacy]],
    ["Risco residual", "O risco que sobra depois das respostas aplicadas. Precisa caber no apetite a risco.", [D.gov]],
    ["Saga", "Sequência de transações locais com compensações, usada para manter a consistência entre serviços. Pode ser orquestrada ou coreografada.", [D.dev]],
    ["SBI", "Modelo de feedback do Center for Creative Leadership: Situação, Comportamento (Behavior), Impacto.", [D.lider, D.retencao]],
    ["SBOM", "Software Bill of Materials: inventário dos componentes e dependências de um software.", [D.devops]],
    ["SCARF", "David Rock: Status, Certeza, Autonomia, Relacionamento e Justiça, cinco domínios de ameaça ou recompensa social.", [D.lider]],
    ["SCI", "Software Carbon Intensity (ISO/IEC 21031:2024): ((E × I) + M) por unidade funcional.", [D.adv]],
    ["SCQA", "Estrutura de apresentação: Situação, Complicação, Questão, Resposta (Barbara Minto).", [D.com]],
    ["SECI", "Nonaka e Takeuchi: Socialização, Externalização, Combinação e Internalização do conhecimento.", [D.mudanca]],
    ["Segurança psicológica", "Crença compartilhada de que o time é seguro para correr riscos interpessoais (Amy Edmondson).", [D.lider, D.equipes]],
    ["Service Blueprint", "Mapa do serviço com ações do cliente, frontstage, backstage e processos de suporte (Lynn Shostack, 1984).", [D.creative]],
    ["SLI, SLO e SLA", "SLI é a medida; SLO, o objetivo interno para ela; SLA, o compromisso contratual com o cliente.", [D.obs]],
    ["SoA", "Declaração de Aplicabilidade da ISO 27001: quais controles se aplicam, por quê e como são implementados.", [D.direito]],
    ["Stay interview", "Conversa com quem fica, para entender o que mantém a pessoa e o que a faria sair.", [D.retencao]],
    ["Strangler Fig", "Migração gradual de um legado, substituindo funcionalidades uma a uma até o sistema antigo poder ser desligado.", [D.arq, D.dev]],
    ["STRIDE", "Modelo de ameaças: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege.", [D.devops]],
    ["TCO", "Custo total de propriedade: licença, infraestrutura, integração, pessoas, suporte e custo de saída.", [D.fin]],
    ["Team Topologies", "Skelton e Pais: times stream-aligned, platform, enabling e complicated-subsystem, com três modos de interação.", [D.equipes]],
    ["TIME", "Método do Gartner para racionalizar aplicações: Tolerate, Invest, Migrate, Eliminate.", [D.ea]],
    ["TOGAF e ADM", "Framework de arquitetura corporativa do The Open Group. O ADM é seu método em fases, da visão à gestão de mudanças.", [D.ea]],
    ["Tuckman", "Estágios de um time: forming, storming, norming, performing (e adjourning).", [D.equipes]],
    ["Unit economics", "Custos e receitas por unidade (cliente, pedido, transação), que ligam custo a valor de negócio.", [D.lean, D.cloud]],
    ["Wardley Map", "Mapa da evolução dos componentes: gênese, customizado, produto e commodity.", [D.fin]],
    ["Well-Architected", "Boas práticas dos provedores de nuvem. Na AWS: excelência operacional, segurança, confiabilidade, performance, custo e sustentabilidade.", [D.cloud]],
    ["Westrum (tipologia)", "Culturas patológica, burocrática e generativa, observadas pela forma como a informação circula.", [D.cultura]],
    ["WIP", "Work in progress: trabalho iniciado e não terminado. Limitar o WIP reduz o lead time.", [D.ageis]],
    ["Working agreement", "Acordo concreto e verificável construído pelo próprio time sobre como trabalhar junto.", [D.cultura, D.equipes]],
    ["WSJF", "Weighted Shortest Job First: Cost of Delay ÷ tamanho do trabalho.", [D.ageis]],
    ["Zachman", "Ontologia de arquitetura: matriz 6×6 de perguntas (o quê, como, onde, quem, quando, por quê) × perspectivas.", [D.ea]]
  ];
})();
