window.CURSO.push({
  n: 1,
  periodo: "Meses 1 e 2",
  titulo: "Digital Strategy & Agile",
  descricao: "A base: o papel do líder técnico, como pensar estratégia com design, como construir produtos digitais e como validar ideias rápido com Lean Startup.",
  disciplinas: [
    {
      titulo: "O Líder de Times Tech",
      resumo: "Liderar times de tecnologia é trocar o papel de quem resolve o problema pelo de quem cria as condições para o time resolver. Esta disciplina cobre as teorias de liderança, os estilos, as competências e a base emocional e neurológica de quem lidera.",
      topicos: [
        { t: "Teoria da liderança",
          c: "<p>As teorias evoluíram de <b>traços</b> (o líder nasce com características especiais) para <b>comportamentais</b> (liderança se aprende e se observa em ações), <b>contingenciais/situacionais</b> (o estilo certo depende do contexto e da maturidade do time) e, mais recentemente, <b>transformacional</b> e <b>servidora</b>.</p><p><b>Na prática:</b> na Liderança Situacional, o nível de desenvolvimento é <b>por tarefa</b>, e não por pessoa. Uma dev sênior que acaba de entrar numa stack nova pode estar muito motivada e ainda sem competência <i>nessa</i> tarefa. Ali ela precisa de direção (instruções claras, exemplos, checkpoints curtos), mas na tarefa que já domina pode receber delegação total. Conforme a competência cresce, o líder passa de dirigir para treinar, depois apoiar e, por fim, delegar.</p><p>Greenleaf propôs um teste para a liderança servidora: as pessoas lideradas estão crescendo, ficando mais saudáveis, mais sábias, mais livres e mais autônomas?</p><p><b>Erros comuns:</b> usar o mesmo estilo com todo mundo; confundir liderança servidora com fazer tudo o que o time pede ou com ausência de direção; manter alguém experiente \"no dirigir\" por falta de confiança.</p>",
          k: ["<b>Liderança Situacional (Hersey & Blanchard):</b> ajusta o estilo (dirigir, treinar, apoiar, delegar) conforme a competência e o comprometimento de cada pessoa.",
              "<b>Transformacional (Bass):</b> inspira por propósito, estímulo intelectual e atenção individual.",
              "<b>Servant Leadership (Greenleaf):</b> o líder existe para remover impedimentos e fazer o time crescer — muito alinhada à cultura ágil.",
              "Em tech: um Tech Lead muitas vezes lidera <i>sem autoridade formal</i>, usando influência técnica e confiança."] },
        { t: "Tipos de líder",
          c: "<p>Goleman descreve seis estilos: <b>coercitivo</b>, <b>visionário (autoritativo)</b>, <b>afiliativo</b>, <b>democrático</b>, <b>pacesetter (modelador)</b> e <b>coach</b>. Os melhores líderes transitam entre eles conforme a situação.</p><p><b>Em uma frase cada</b> (Goleman, HBR 2000): coercitivo, \"faça o que eu digo\"; visionário, \"venha comigo\"; afiliativo, \"as pessoas vêm primeiro\"; democrático, \"o que você acha?\"; pacesetter, \"faça como eu, agora\"; coach, \"tente isto\". Na pesquisa com quase 4 mil executivos, o visionário foi o estilo com o efeito mais positivo no clima, e o coercitivo e o pacesetter, os de efeito mais negativo. Os líderes com os melhores climas dominavam quatro ou mais estilos.</p><p><b>Exemplo:</b> durante um incidente grave, o líder é diretivo por algumas horas (\"você reverte o deploy, você fala com o suporte\"). No dia seguinte, no post-mortem, muda para coach e deixa o time chegar às causas e às ações.</p><p><b>Erros comuns:</b> ficar preso no estilo que funcionou na última crise; confundir o democrático com decidir tudo por consenso, mesmo quando há urgência.</p>",
          k: ["Visionário e coach geram o clima mais positivo no longo prazo.",
              "Pacesetter é armadilha comum de ex-devs promovidos: \"faço eu mesmo, mais rápido\" — funciona pouco tempo e desgasta o time.",
              "Coercitivo só em crise real (ex.: incidente grave em produção).",
              "Diferencie também: Tech Lead (foco técnico), Engineering Manager (foco em pessoas e entrega), Staff/Principal (foco em arquitetura e influência transversal)."] },
        { t: "Competência de um líder",
          c: "<p>Competência = <b>CHA</b>: Conhecimento, Habilidade e Atitude. Para líderes tech, combine competências técnicas (entender arquitetura e trade-offs), de negócio (entender valor, custo e cliente) e humanas (comunicação, feedback, desenvolvimento de pessoas).</p><p><b>Feedback com o modelo SBI</b> (Situação, Comportamento, Impacto — Center for Creative Leadership): \"Na daily de ontem (situação), você interrompeu a Ana duas vezes enquanto ela explicava o bloqueio (comportamento). Ela parou de falar e o problema só apareceu hoje, atrasando a entrega (impacto).\" O modelo descreve fatos observáveis, sem rótulos como \"você é desrespeitoso\".</p><p><b>Delegação em níveis:</b> o Delegation Poker (Management 3.0) propõe sete níveis entre \"eu decido e comunico\" e \"delegação total\": contar, vender, consultar, concordar, aconselhar, perguntar depois e delegar. Combinar o nível de cada tipo de decisão (escolher bibliotecas, contratar, mudar o processo do time) evita tanto o microgerenciamento quanto a surpresa.</p><p><b>Erros comuns:</b> feedback só na avaliação anual; delegar a tarefa sem a autoridade para decidir; decidir sem registrar o contexto, e depois ninguém lembra por quê.</p>",
          k: ["Dar e receber feedback com frequência.",
              "Delegar resultados, não tarefas.",
              "Tomar decisões com informação incompleta e registrar o porquê.",
              "Traduzir técnico ↔ negócio para stakeholders."] },
        { t: "Autogestão",
          c: "<p>Antes de gerir os outros, gerir a si: tempo, energia, prioridades e limites. O líder vira referência de ritmo — se trabalha até de madrugada, o time entende que isso é esperado.</p><p><b>Na prática:</b> a Matriz de Eisenhower vira quatro ações: <b>fazer</b> (urgente e importante), <b>agendar</b> (importante, não urgente: 1:1s, planejamento, estudo), <b>delegar</b> (urgente, pouco importante) e <b>eliminar</b> (nenhum dos dois). O quadrante \"agendar\" é o que mais some da agenda de quem lidera, e é nele que ficam as atividades que evitam crises futuras.</p><p>Paul Graham explica que, para quem constrói (maker), a unidade de tempo é meio dia: uma reunião no meio da tarde pode destruir a tarde inteira. O líder, que vive no horário de gestor, deve agrupar suas reuniões com o time e proteger os blocos de foco das pessoas.</p><p><b>Erros comuns:</b> virar gargalo de aprovações; responder mensagens a qualquer hora e criar essa expectativa no time; agenda 100% cheia, sem espaço para imprevistos.</p>",
          k: ["Matriz de Eisenhower (urgente × importante).",
              "Time blocking: separe blocos de foco (maker time) dos de reuniões (manager time) — conceito de Paul Graham.",
              "Revisão semanal: o que avançou, o que travou, o que delegar.",
              "Limites saudáveis como exemplo para o time."] },
        { t: "Inteligência Emocional",
          c: "<p>Modelo de Daniel Goleman com cinco pilares: <b>autoconsciência</b>, <b>autorregulação</b>, <b>motivação</b>, <b>empatia</b> e <b>habilidades sociais</b>. Em situações de pressão (deadline, incidente, conflito) é o que separa uma reação impulsiva de uma resposta útil.</p><p><b>Segurança psicológica</b>, segundo Amy Edmondson, é a crença compartilhada de que o time é seguro para correr riscos interpessoais: perguntar, admitir erro, discordar. No Projeto Aristóteles, o Google a identificou como a dinâmica mais importante entre os times eficazes. Edmondson sugere três atitudes do líder: apresentar o trabalho como problema de aprendizado (não de execução), reconhecer a própria falibilidade (\"posso estar deixando passar algo\") e fazer muitas perguntas.</p><p><b>Exemplo:</b> um deploy derruba o checkout. Um líder reativo pergunta em público \"quem fez isso?\". Um líder com autorregulação pergunta \"o que precisamos agora para restaurar?\" e deixa o \"como isso passou?\" para o post-mortem, focado no sistema.</p><p><b>Erros comuns:</b> confundir autorregulação com reprimir emoções; confundir segurança psicológica com ausência de cobrança (para Edmondson, altos padrões e segurança devem andar juntos).</p>",
          k: ["Nomeie a emoção antes de agir (\"estou frustrado porque…\").",
              "Pausa entre estímulo e resposta.",
              "Empatia não é concordar — é entender o ponto de vista do outro.",
              "Segurança psicológica (Amy Edmondson) depende muito da IE do líder."] },
        { t: "Neurociência na liderança",
          c: "<p>O cérebro reage a ameaças sociais como a ameaças físicas. O modelo <b>SCARF</b> (David Rock) mapeia cinco domínios que disparam ameaça ou recompensa: <b>Status, Certeza, Autonomia, Relacionamento (Relatedness) e Justiça (Fairness)</b>.</p><p><b>De onde vem:</b> estudos de Eisenberger e Lieberman (2003) mostraram que a exclusão social ativa regiões do cérebro ligadas à dor física. Os trabalhos de Amy Arnsten mostram que o estresse agudo prejudica o córtex pré-frontal, responsável por planejamento e raciocínio. O SCARF é um <b>modelo prático</b> inspirado nesses achados, e não uma lei do cérebro: use-o como checklist, não como diagnóstico.</p><p><b>Na prática:</b> antes de anunciar uma mudança, passe pelos cinco domínios. <b>Status:</b> alguém perde papel ou visibilidade? <b>Certeza:</b> o que ainda não se sabe e quando se saberá? <b>Autonomia:</b> o que o time ainda pode decidir? <b>Relacionamento:</b> quem deixa de trabalhar junto? <b>Justiça:</b> o critério é claro e igual para todos?</p><p><b>Erros comuns:</b> dizer \"nada vai mudar\" quando vai (destrói a Certeza no primeiro imprevisto); decidir em segredo e anunciar pronto, o que ataca Autonomia e Justiça ao mesmo tempo.</p>",
          k: ["Reorganizações mexem com Certeza e Status — comunique cedo e com clareza.",
              "Microgerenciamento ataca Autonomia.",
              "Sob ameaça, a amígdala reduz a capacidade do córtex pré-frontal (raciocínio, criatividade).",
              "Reconhecimento e progresso visível ativam o sistema de recompensa (dopamina)."] }
      ],
      pratica: "<p>Faça uma autoavaliação: para cada estilo de Goleman, anote uma situação recente em que você o usou e qual foi o resultado. Depois, mapeie cada pessoa do seu time (ou de um time fictício) na matriz da Liderança Situacional e defina o estilo mais adequado para cada uma.</p>",
      perguntas: [
        ["Qual a diferença entre liderança situacional e servidora?", "A situacional adapta o estilo à maturidade de cada liderado; a servidora é uma postura geral de colocar o time em primeiro lugar e remover obstáculos. Elas se complementam."],
        ["Por que o estilo pacesetter é arriscado para quem acabou de ser promovido?", "Porque o líder passa a ser o gargalo, não desenvolve o time e gera desmotivação; o resultado de curto prazo esconde a perda de capacidade do time."],
        ["O que significa cada letra do SCARF?", "Status, Certainty (Certeza), Autonomy, Relatedness (Relacionamento), Fairness (Justiça)."],
        ["Na Liderança Situacional, qual estilo usar com alguém muito motivado mas sem experiência na tarefa?", "Dirigir: instruções claras e acompanhamento próximo. O nível é avaliado por tarefa, então a mesma pessoa pode receber delegação em outro assunto."],
        ["O que é segurança psicológica segundo Amy Edmondson?", "A crença compartilhada de que o time é seguro para correr riscos interpessoais, como perguntar, admitir erros e discordar, sem ser punido ou humilhado."],
        ["Qual a diferença entre o horário de maker e o de manager (Paul Graham)?", "Quem constrói precisa de blocos longos, de meio dia; quem gerencia trabalha em intervalos de uma hora. Uma reunião no meio do bloco custa muito mais para o maker."],
        ["O que o modelo SBI evita num feedback?", "Rótulos e julgamentos sobre a pessoa. Ele descreve a situação, o comportamento observável e o impacto."],
        ["Situação: você foi promovido a tech lead, ainda faz os PRs mais complexos e revisa todos os outros. O time vive esperando você. O que muda?", "É o padrão pacesetter, e você virou gargalo. Distribua as revisões, faça par nas partes complexas em vez de fazer sozinho, combine níveis de delegação para as decisões técnicas e proteja tempo para 1:1s e planejamento."]
      ],
      aprofundamento: [
        ["OpenStax — <i>Principles of Management</i>, cap. 13 \"Leadership\"", "https://openstax.org/books/principles-management/pages/13-introduction", "livro-texto aberto (em inglês): traços, comportamental, situacional, transacional × transformacional. Comece por aqui."],
        ["Greenleaf, R. K. — <i>The Servant as Leader</i> (1970)", "https://archive.org/details/20200601-the-servant-as-leader", "o ensaio original da liderança servidora (Internet Archive)."],
        ["Greenleaf — ensaio gratuito da Berrett-Koehler", "https://ideas.bkconnection.com/power-of-servant-leadership", "Greenleaf revisita a liderança servidora 10 anos depois."],
        ["Google re:Work — Project Oxygen", "https://rework.withgoogle.com/intl/en/guides/following-the-data-the-research-behind-great-managers", "pesquisa sobre os comportamentos de bons gestores + questionário de autoavaliação."],
        ["FGV — Liderança na Era das Competências", "https://educacao-executiva.fgv.br/cursos/online/curta-media-duracao-online/lideranca-na-era-das-competencias", "curso gratuito em português, com declaração de participação."],
        ["FGV — catálogo de cursos gratuitos", "https://educacao-executiva.fgv.br/cursos/gratuitos", ""],
        ["ENAP — Escola Virtual.Gov", "https://www.escolavirtual.gov.br", "mais de 1.500 cursos gratuitos com certificado, com trilhas de liderança."],
        ["MIT OpenCourseWare — Practical Leadership", "https://ocw.mit.edu/courses/15-974-practical-leadership-fall-2004/", "ementa, leituras e exercícios da MIT Sloan."],
        ["MIT OpenCourseWare — Organizational Leadership and Change", "https://ocw.mit.edu/courses/15-317-organizational-leadership-and-change-summer-2009/", "continuação natural do anterior."],
        ["Will Larson — lethain.com", "https://lethain.com/", "blog sobre liderança em engenharia."],
        ["Lara Hogan — blog", "https://larahogan.me/blog/", "ferramentas práticas para 1:1, feedback e gestão de times."]
      ],
      referencias: [
        ["Hersey, P.; Blanchard, K. <i>Management of Organizational Behavior</i> — Liderança Situacional", ""],
        ["Greenleaf, R. K. <i>Servant Leadership</i> (1977) — Greenleaf Center", "https://www.greenleaf.org/what-is-servant-leadership/"],
        ["Bass, B. M. <i>Leadership and Performance Beyond Expectations</i> (1985) — liderança transformacional", ""],
        ["Goleman, D. \"Leadership That Gets Results\" — Harvard Business Review (2000) — os 6 estilos", "https://hbr.org/2000/03/leadership-that-gets-results"],
        ["Goleman, D. <i>Inteligência Emocional</i> (1995) e <i>Liderança Primal</i> (2002)", ""],
        ["Rock, D. \"SCARF: a brain-based model for collaborating with and influencing others\" — NeuroLeadership Journal (2008)", "https://neuroleadership.com/"],
        ["Graham, P. \"Maker's Schedule, Manager's Schedule\" (2009)", "https://paulgraham.com/makersschedule.html"],
        ["Fournier, C. <i>The Manager's Path</i> (O'Reilly, 2017)", ""],
        ["Larson, W. <i>An Elegant Puzzle</i> (2019) e blog lethain.com", "https://lethain.com/"],
        ["Edmondson, A. \"Psychological Safety and Learning Behavior in Work Teams\" — Administrative Science Quarterly (1999) e <i>The Fearless Organization</i> (2018)", ""],
        ["Google re:Work — Understand team effectiveness (Projeto Aristóteles)", "https://rework.withgoogle.com/intl/en/guides/understand-team-effectiveness"],
        ["Center for Creative Leadership — modelo SBI (Situation-Behavior-Impact)", ""],
        ["Management 3.0 — Delegation Poker", "https://management30.com/practice/delegation-poker/"],
        ["Eisenberger, N.; Lieberman, M.; Williams, K. \"Does Rejection Hurt?\" — Science (2003)", ""],
        ["Arnsten, A. \"Stress signalling pathways that impair prefrontal cortex structure and function\" — Nature Reviews Neuroscience (2009)", ""]
      ]
    },
    {
      titulo: "IT Creative Strategy",
      resumo: "Ferramentas de design aplicadas à estratégia: entender profundamente o problema e o usuário antes de escolher a solução tecnológica.",
      topicos: [
        { t: "Design Thinking",
          c: "<p>Abordagem centrada no humano para resolver problemas complexos. No modelo da d.school de Stanford são cinco etapas: <b>Empatizar → Definir → Idear → Prototipar → Testar</b>. O <b>Double Diamond</b> (Design Council) resume em divergir/convergir no problema e depois divergir/convergir na solução.</p><p>As quatro fases do Double Diamond são <b>Descobrir</b> e <b>Definir</b> (primeiro diamante: o problema) e <b>Desenvolver</b> e <b>Entregar</b> (segundo diamante: a solução).</p><p><b>Exemplo:</b> um banco vê muitos abandonos na abertura de conta pelo app. Em vez de \"refazer a tela\", o time entrevista quem desistiu e descobre que muita gente para na selfie com documento. A pergunta vira \"Como poderíamos ajudar quem não tem o documento em mãos a terminar o cadastro depois?\". Da ideação saem opções (salvar e continuar depois, lembrete, foto do documento digital), que são prototipadas e testadas com 5 a 8 pessoas antes de qualquer código.</p><p><b>Erros comuns:</b> workshop de um dia com post-its, sem pesquisa com usuários reais nem teste depois; chegar ao processo com a solução já decidida.</p>",
          k: ["Ferramentas: entrevistas, mapa de empatia, personas, \"Como poderíamos…?\" (HMW), brainstorming, crazy 8s.",
              "Erro comum: pular direto para a solução sem validar o problema.",
              "É um processo iterativo, não linear."] },
        { t: "Design de Serviços",
          c: "<p>Olha para a experiência completa do serviço, incluindo o que o cliente não vê. A ferramenta principal é o <b>Service Blueprint</b>: ações do cliente, frontstage (pontos de contato visíveis), backstage (processos internos) e processos de suporte (sistemas).</p><p>O blueprint foi proposto por Lynn Shostack na HBR (1984). As camadas são separadas por três linhas: a <b>linha de interação</b> (entre cliente e empresa), a <b>linha de visibilidade</b> (o que o cliente vê e o que não vê) e a <b>linha de interação interna</b> (entre a linha de frente e o suporte). No topo ficam as <b>evidências físicas</b>: telas, e-mails, SMS.</p><p><b>Exemplo:</b> na abertura de conta, o cliente envia a selfie (ação) e vê \"em análise\" (frontstage). Nos bastidores, a validação automática falha em 15% dos casos, que caem numa fila manual (backstage) cujo sistema de antifraude só roda em lotes de hora em hora (suporte). O blueprint mostra que o problema de experiência é um processo interno, não a tela.</p><p><b>Erros comuns:</b> desenhar só o caminho feliz; montar o blueprint sem as áreas que operam os bastidores.</p>",
          k: ["Mostra onde a tecnologia sustenta — ou quebra — a experiência.",
              "Ótimo para achar gargalos entre áreas.",
              "Complementa a jornada do usuário com a visão operacional."] },
        { t: "Design Estratégico",
          c: "<p>Usa o pensamento de design para decisões de negócio: posicionamento, portfólio e modelo de negócio. Ferramentas típicas: <b>Business Model Canvas</b>, <b>Value Proposition Canvas</b>, construção de cenários futuros.</p><p>O <b>Business Model Canvas</b> tem nove blocos: segmentos de clientes, proposta de valor, canais, relacionamento com clientes, fontes de receita, recursos-chave, atividades-chave, parcerias-chave e estrutura de custos. O <b>Value Proposition Canvas</b> dá zoom na relação entre segmento e proposta de valor e busca o <i>fit</i>: a oferta alivia as dores e cria os ganhos que mais importam para o cliente.</p><p><b>Na prática:</b> para um tech lead, o canvas mostra por que uma decisão técnica é estratégica. Se \"parcerias-chave\" inclui um provedor de pagamentos, a integração com ele é um risco de negócio, e não só de TI. Osterwalder e Pigneur tratam cada bloco preenchido como <b>hipótese</b> a ser testada, e não como fato.</p><p><b>Erros comuns:</b> preencher o canvas uma vez e guardar; misturar vários segmentos de clientes num único canvas; listar funcionalidades como se fossem proposta de valor.</p>",
          k: ["Liga a visão da empresa ao que o time constrói.",
              "Value Proposition Canvas: jobs, dores e ganhos do cliente × produtos, aliviadores de dor e criadores de ganho."] },
        { t: "CX/UX",
          c: "<p><b>UX</b> (User Experience) é a experiência de uso de um produto específico; <b>CX</b> (Customer Experience) é a percepção total do cliente sobre a marca, em todos os canais. UX é parte de CX.</p><p><b>Como ler as métricas:</b> o <b>NPS</b> (Reichheld, HBR, 2003) pergunta, de 0 a 10, a chance de recomendar a empresa: NPS = % de promotores (9–10) − % de detratores (0–6), numa escala de −100 a +100. O <b>SUS</b> tem 10 itens com 5 opções de resposta, e a média de referência é 68: acima disso, a usabilidade percebida está acima da média. CSAT mede a satisfação com uma interação; CES, o esforço para resolver algo.</p><p><b>Na prática:</b> combine uma métrica de relação (NPS), uma de interação (CSAT ou CES) e uma de comportamento (taxa de conclusão de tarefa). Nas notas baixas, leia o comentário aberto: é ali que aparece o <i>porquê</i>.</p><p><b>Erros comuns:</b> usar o NPS como única métrica e como meta de bônus; perguntar a nota logo depois de um erro, o que distorce a amostra; tratar UX como \"deixar a tela bonita\" e ignorar a jornada completa, incluindo atendimento e cobrança.</p>",
          k: ["Heurísticas de Nielsen (10 princípios de usabilidade).",
              "Métricas: NPS, CSAT, CES (Customer Effort Score), taxa de conclusão de tarefa, SUS.",
              "Jornada do cliente: etapas, pontos de contato, emoções, momentos da verdade.",
              "Acessibilidade (WCAG) faz parte de UX."] }
      ],
      pratica: "<p>Escolha um serviço que você usa (ex.: abrir conta num banco digital). Monte um Service Blueprint com as quatro camadas e aponte três pontos de falha em que a tecnologia poderia melhorar a experiência.</p>",
      perguntas: [
        ["Quais as cinco etapas do Design Thinking segundo a d.school?", "Empatizar, Definir, Idear, Prototipar e Testar."],
        ["Qual a diferença entre CX e UX?", "UX é a experiência de uso de um produto/interface; CX é a experiência total com a empresa, em todos os pontos de contato."],
        ["O que o Service Blueprint mostra que uma jornada do usuário não mostra?", "Os bastidores: processos internos, sistemas e áreas de suporte que sustentam cada ponto de contato."],
        ["Quais as quatro fases do Double Diamond?", "Descobrir, Definir, Desenvolver e Entregar."],
        ["Quais as três linhas que dividem um Service Blueprint?", "Linha de interação, linha de visibilidade e linha de interação interna."],
        ["Como se calcula o NPS?", "Percentual de promotores (notas 9 e 10) menos o percentual de detratores (notas 0 a 6). O resultado vai de −100 a +100."],
        ["Por que tratar os blocos do Business Model Canvas como hipóteses?", "Porque, no início, eles são suposições sobre clientes, canais e receitas. Precisam ser testados, e o canvas deve mudar conforme o que se aprende."],
        ["Situação: a diretoria quer um app novo \"porque o concorrente lançou\". Como você usa as ferramentas desta disciplina?", "Volte ao problema: pesquise quais necessidades dos seus clientes o app do concorrente atende (primeiro diamante), mapeie a jornada e o blueprint atuais para ver onde a experiência falha e só então compare soluções. Talvez o problema se resolva sem um app novo."]
      ],
      aprofundamento: [
        ["Stanford d.school — Design Thinking Bootleg", "https://dschool.stanford.edu/tools/design-thinking-bootleg", "baralho gratuito (PDF, Creative Commons) com 30+ ferramentas para as 5 etapas. Comece por aqui."],
        ["IDEO.org — Design Kit", "https://www.designkit.org/", "métodos de design centrado no humano, com o <i>Field Guide</i> em PDF gratuito (57 métodos + worksheets)."],
        ["This is Service Design Doing — Method Library", "https://www.thisisservicedesigndoing.com/methods", "54 métodos de design de serviços completos, gratuitos online ou em PDF (o mesmo conteúdo do livro de métodos)."],
        ["NN/g — Journey Mapping 101", "https://www.nngroup.com/articles/journey-mapping-101/", "como montar uma jornada do usuário."],
        ["NN/g — Service Blueprinting FAQ", "https://www.nngroup.com/articles/service-blueprinting-faq/", "dúvidas práticas sobre blueprint; complementa o artigo das referências."],
        ["NN/g — UX Mapping Methods: Study Guide", "https://www.nngroup.com/articles/ux-mapping-methods-study-guide/", "trilha de leitura sobre mapa de empatia, jornada, blueprint etc."],
        ["Strategyzer — Business Model Canvas (template oficial)", "https://www.strategyzer.com/library/the-business-model-canvas", "PDF gratuito para imprimir."],
        ["Strategyzer — Value Proposition Canvas (template oficial)", "https://www.strategyzer.com/library/the-value-proposition-canvas", "PDF gratuito para imprimir."],
        ["Interaction Design Foundation — Literature", "https://ixdf.org/literature", "enciclopédias e artigos abertos de UX/IHC."]
      ],
      referencias: [
        ["Stanford d.school — modelo de 5 etapas do Design Thinking", "https://dschool.stanford.edu/"],
        ["Design Council (UK) — Double Diamond", "https://www.designcouncil.org.uk/our-resources/the-double-diamond/"],
        ["Brown, T. <i>Design Thinking</i> (Change by Design, 2009)", ""],
        ["Stickdorn, M. et al. <i>This is Service Design Doing</i> (O'Reilly, 2018) — Service Blueprint", ""],
        ["Nielsen Norman Group — Service Blueprints: Definition", "https://www.nngroup.com/articles/service-blueprints-definition/"],
        ["Nielsen, J. — 10 Usability Heuristics for User Interface Design", "https://www.nngroup.com/articles/ten-usability-heuristics/"],
        ["Osterwalder, A.; Pigneur, Y. <i>Business Model Generation</i> e <i>Value Proposition Design</i> — Strategyzer", "https://www.strategyzer.com/"],
        ["W3C — Web Content Accessibility Guidelines (WCAG)", "https://www.w3.org/WAI/standards-guidelines/wcag/"],
        ["Shostack, G. L. \"Designing Services That Deliver\" — Harvard Business Review (1984)", "https://hbr.org/1984/01/designing-services-that-deliver"],
        ["Reichheld, F. \"The One Number You Need to Grow\" — Harvard Business Review (2003)", "https://hbr.org/2003/12/the-one-number-you-need-to-grow"],
        ["MeasuringU (Jeff Sauro) — System Usability Scale (SUS)", "https://measuringu.com/sus/"]
      ]
    },
    {
      titulo: "Estratégia de Produtos Digitais",
      resumo: "Como sair de uma visão de produto até a entrega e a evolução contínua, equilibrando valor para o cliente, viabilidade técnica e viabilidade de negócio.",
      topicos: [
        { t: "Visão estratégica de produtos digitais",
          c: "<p>Um produto digital precisa de <b>visão</b> (onde queremos chegar), <b>estratégia</b> (como vamos chegar) e <b>roadmap</b> (em que ordem). Marty Cagan destaca que times de produto devem ser <b>empoderados para resolver problemas</b>, não fábricas de features.</p><p><b>Na prática:</b> um roadmap de outcomes troca \"lançar chat no app (T3)\" por \"reduzir em 20% os contatos no SAC sobre status do pedido\" e deixa a solução para o time descobrir. Melissa Perri chama de <i>build trap</i> a situação da empresa que mede o sucesso pela quantidade de features entregues, e não pelo valor gerado.</p><p>Uma boa North Star reflete valor para o cliente, pode ser influenciada pelo time e vem antes da receita. Em um app de delivery, por exemplo, \"pedidos entregues no prazo por semana\" diz mais que \"downloads\" (métrica de vaidade) ou \"faturamento\" (resultado que chega atrasado).</p><p><b>Erros comuns:</b> roadmap com datas e features fechadas para 12 meses; visão tão genérica que não ajuda a dizer não; North Star que o time não consegue mover.</p>",
          k: ["Product Vision Board (Roman Pichler): público, necessidades, produto, objetivos de negócio.",
              "Roadmap orientado a resultados (outcomes), não a entregas (outputs).",
              "North Star Metric: a métrica que melhor captura o valor entregue ao cliente."] },
        { t: "Product Discovery & Design",
          c: "<p>Discovery é descobrir <b>o que</b> construir, reduzindo quatro riscos (Cagan): <b>valor</b> (vão querer?), <b>usabilidade</b> (vão conseguir usar?), <b>viabilidade técnica</b> (conseguimos construir?) e <b>viabilidade de negócio</b> (funciona para a empresa?).</p><p><b>Na prática:</b> Cagan distribui os riscos pelo trio: o PM responde por valor e viabilidade de negócio, o designer pela usabilidade e o tech lead pela viabilidade técnica. Teresa Torres recomenda entrevistas semanais sobre histórias reais (\"conte a última vez que você…\"), e não perguntas hipotéticas (\"você usaria…?\"). Ela também recomenda testar as <b>suposições</b> mais arriscadas de cada solução, e não a solução inteira.</p><p>Testes baratos: protótipo navegável, <i>fake door</i> (um botão para uma função que ainda não existe, que mede o interesse) e concierge (fazer à mão o que o produto faria).</p><p><b>Erros comuns:</b> tratar discovery como uma fase que \"acaba\" antes do delivery; fazer pesquisa só para confirmar a solução já decidida; chamar o tech lead só depois que a solução está desenhada.</p>",
          k: ["Opportunity Solution Tree (Teresa Torres): outcome → oportunidades → soluções → experimentos.",
              "Continuous Discovery: falar com clientes toda semana.",
              "Protótipos de baixa fidelidade antes de código.",
              "Trio de produto: PM + Design + Tech Lead."] },
        { t: "Do Product Discovery ao Rollout",
          c: "<p>Depois de validar, o <b>Delivery</b> transforma a solução em software de produção. O rollout deve ser gradual e reversível.</p><p><b>Exemplo:</b> o novo checkout vai para produção desligado por uma feature flag. Ele é ligado primeiro para funcionários e depois para 5% dos clientes, enquanto o time acompanha erros, latência e conversão. Se a conversão cair, basta desligar a flag, sem novo deploy.</p><p>Pete Hodgson classifica as flags em quatro tipos: <b>release toggles</b> (vida curta, escondem trabalho em andamento), <b>experiment toggles</b> (testes A/B), <b>ops toggles</b> (desligar funções pesadas sob carga) e <b>permission toggles</b> (liberar funções para certos grupos de usuários).</p><p><b>Erros comuns:</b> flags que nunca são removidas e viram dívida técnica (a remoção faz parte da entrega); encerrar um teste A/B antes de ter amostra suficiente; começar o rollout sem critério de parada definido.</p>",
          k: ["Feature flags para separar deploy de release.",
              "Canary release e rollout percentual (1% → 10% → 50% → 100%).",
              "Testes A/B para medir o impacto real.",
              "Dual-track agile: discovery e delivery rodando em paralelo."] },
        { t: "Ciclo de vida de produto de software",
          c: "<p>Produtos passam por <b>Introdução → Crescimento → Maturidade → Declínio</b>. Cada fase pede estratégias, métricas e até perfis de time diferentes.</p><p><b>Na prática:</b> Levitt já alertava que a curva não é destino: novos usos, novos mercados e novas versões podem estender a maturidade. Descontinuar também é decisão de produto. Um sunset bem feito avisa os clientes com antecedência, oferece caminho de migração, bloqueia novas adesões antes de desligar e acompanha quantos clientes ainda dependem da função.</p><p><b>Erros comuns:</b> tratar um produto maduro com a mesma estratégia de experimentação do início; manter produtos em declínio sem dono, acumulando custo e risco de segurança.</p>",
          k: ["Introdução: busca por product-market fit, muita experimentação.",
              "Crescimento: escala, performance, aquisição.",
              "Maturidade: eficiência, retenção, redução de custo.",
              "Declínio: sunset planejado, migração de clientes, redução de dívida técnica.",
              "Não confunda com o SDLC (ciclo de desenvolvimento: requisitos, design, código, teste, deploy, manutenção)."] }
      ],
      pratica: "<p>Monte uma Opportunity Solution Tree para um produto que você conhece: defina um outcome mensurável, liste três oportunidades (dores/desejos), duas soluções para cada uma e um experimento barato para validar a solução mais promissora.</p>",
      perguntas: [
        ["Quais são os quatro riscos de produto segundo Marty Cagan?", "Valor, usabilidade, viabilidade técnica e viabilidade de negócio."],
        ["Por que separar deploy de release?", "Para colocar código em produção sem expor ao usuário, fazendo liberação gradual, testes e rollback instantâneo via feature flag."],
        ["O que é North Star Metric?", "Uma métrica única que representa o valor central entregue ao cliente e antecipa o crescimento sustentável do negócio."],
        ["Qual a diferença entre um roadmap de outputs e um de outcomes?", "O de outputs lista entregas (\"lançar chat no T3\"); o de outcomes lista mudanças mensuráveis de comportamento ou resultado (\"reduzir em 20% os contatos no SAC sobre status do pedido\") e deixa a solução em aberto."],
        ["Na Opportunity Solution Tree, o que fica entre o outcome e as soluções, e por quê?", "As oportunidades: necessidades, dores e desejos dos clientes descobertos em pesquisa. Elas evitam pular direto para a solução e permitem comparar alternativas para o mesmo problema."],
        ["Quais os quatro tipos de feature toggle segundo Pete Hodgson?", "Release, experiment, ops e permission toggles."],
        ["Por que \"downloads\" costuma ser uma North Star ruim?", "É métrica de vaidade: não mostra se o cliente recebeu valor nem prevê retenção ou receita."],
        ["Situação: o CEO traz uma feature \"que o maior cliente pediu\" e quer no próximo sprint. Como você age?", "Entenda o problema por trás do pedido, avalie os quatro riscos, compare com o outcome atual do time e, se possível, valide com um experimento barato. Depois, deixe explícito o trade-off: o que sai do plano para que isso entre."]
      ],
      aprofundamento: [
        ["SVPG — artigos de Marty Cagan", "https://www.svpg.com/articles/", "blog gratuito com boa parte das ideias de <i>Inspired</i> e <i>Empowered</i>. Comece por \"The Four Big Risks\"."],
        ["Product Talk — Teresa Torres", "https://www.producttalk.org/", "artigos gratuitos sobre continuous discovery."],
        ["Product Talk — Getting started with discovery", "https://www.producttalk.org/getting-started-with-discovery/", "guia prático de como começar."],
        ["Basecamp — <i>Shape Up</i> (Ryan Singer)", "https://basecamp.com/shapeup", "livro completo e gratuito: como transformar ideias em projetos com escopo fechado, em ciclos de 6 semanas."],
        ["Roman Pichler — ferramentas gratuitas", "https://www.romanpichler.com/tools/", "templates do Product Vision Board e do GO Product Roadmap, com checklists."],
        ["Roman Pichler — Product Strategy Framework (PDF)", "https://www.romanpichler.com/downloads/tools/Romans-Product-Strategy-Framework.pdf", "visão → estratégia → roadmap → backlog em uma página."]
      ],
      referencias: [
        ["Cagan, M. <i>Inspired</i> (2ª ed., 2017) e <i>Empowered</i> (2020) — Silicon Valley Product Group", "https://www.svpg.com/articles/"],
        ["Cagan, M. \"The Four Big Risks\" — SVPG", "https://www.svpg.com/four-big-risks/"],
        ["Torres, T. <i>Continuous Discovery Habits</i> (2021) — Opportunity Solution Tree", "https://www.producttalk.org/opportunity-solution-tree/"],
        ["Pichler, R. — Product Vision Board", "https://www.romanpichler.com/tools/product-vision-board/"],
        ["Perri, M. <i>Escaping the Build Trap</i> (O'Reilly, 2018)", ""],
        ["Fowler, M. — Feature Toggles (Pete Hodgson)", "https://martinfowler.com/articles/feature-toggles.html"],
        ["Levitt, T. \"Exploit the Product Life Cycle\" — Harvard Business Review (1965)", "https://hbr.org/1965/11/exploit-the-product-life-cycle"]
      ]
    },
    {
      titulo: "Lean Startup",
      resumo: "Método para criar produtos em condições de extrema incerteza, com ciclos curtos de aprendizado validado.",
      topicos: [
        { t: "Inovação",
          c: "<p>Clayton Christensen diferencia <b>inovação sustentadora</b> (melhora produtos existentes para clientes atuais) de <b>inovação disruptiva</b> (começa simples, num mercado ignorado, e sobe até tomar o mercado principal). O modelo dos <b>3 Horizontes</b> (McKinsey) ajuda a equilibrar o portfólio: H1 core, H2 negócios emergentes, H3 apostas futuras.</p><p><b>Na prática:</b> para Christensen, disrupção tem ponto de partida específico. Ela começa pela <b>base do mercado</b> (clientes pouco lucrativos que os líderes ignoram) ou por um <b>mercado novo</b> (quem antes não consumia). No artigo de 2015, os autores argumentam que o Uber <i>não</i> é disruptivo nesse sentido, porque começou atendendo o cliente principal do táxi com um serviço igual ou melhor. Nagji e Tuff (HBR, 2012) propõem dividir o portfólio de inovação em <b>core</b>, <b>adjacente</b> e <b>transformacional</b>, na proporção de referência 70/20/10.</p><p><b>Erros comuns:</b> chamar qualquer novidade de disrupção; avaliar apostas de H3 com as metas de receita do H1 e matá-las cedo; ter só H1 no portfólio e ser pego de surpresa.</p>",
          k: ["Inovação incremental × radical.",
              "Dilema do inovador: empresas líderes falham justamente por atender bem seus melhores clientes.",
              "Uma regra comum de alocação: 70/20/10 entre H1, H2 e H3."] },
        { t: "Validação de ideias",
          c: "<p>O ciclo <b>Construir → Medir → Aprender</b> (Eric Ries) deve ser percorrido o mais rápido possível. Transforme a ideia em <b>hipóteses testáveis</b> e defina de antemão o critério de sucesso.</p><p><b>Exemplo:</b> \"Acreditamos que donos de pequenos restaurantes perdem tempo conciliando pagamentos de vários apps de delivery. Saberemos que é verdade quando 6 de 10 entrevistados contarem, sem a gente sugerir, que fazem isso toda semana, e quando 30% dos visitantes da landing page deixarem o e-mail.\"</p><p><b>The Mom Test</b> (Fitzpatrick) resume as entrevistas em três regras: fale da vida da pessoa, não da sua ideia; pergunte sobre situações concretas do passado, não sobre opiniões ou o futuro; fale menos e escute mais. \"Você usaria?\" gera elogio educado; \"como você resolveu isso da última vez?\" gera dado.</p><p>Ries chama de <b>contabilidade da inovação</b> o processo de medir o ponto de partida, fazer ajustes para mover as métricas e decidir se pivota ou persevera. A <b>análise por coorte</b> (grupos de clientes pela data de entrada) mostra se cada mudança melhorou o comportamento dos novos clientes.</p><p><b>Erros comuns:</b> definir o critério de sucesso depois de ver os dados; entrevistar só amigos e fãs; tratar elogio como validação.</p>",
          k: ["Formato de hipótese: \"Acreditamos que [persona] tem [problema]. Saberemos que é verdade quando [métrica] atingir [valor].\"",
              "Teste as hipóteses mais arriscadas primeiro (leap-of-faith assumptions).",
              "Entrevistas de problema (The Mom Test): pergunte sobre o passado, não sobre opiniões do futuro.",
              "Evite métricas de vaidade (downloads totais); use métricas acionáveis (conversão por coorte)."] },
        { t: "MVP e Pivot",
          c: "<p><b>MVP</b> é a menor coisa que gera aprendizado validado — não necessariamente um produto. <b>Pivot</b> é uma mudança estruturada de rota mantendo o que já foi aprendido.</p><p><b>Exemplos do livro de Ries:</b> o Dropbox validou a demanda com um vídeo que mostrava o produto funcionando, e a lista de espera do beta passou de 5 mil para 75 mil pessoas em uma noite. O fundador da Zappos testou se as pessoas comprariam sapatos online fotografando os pares em lojas locais; quando alguém comprava, ele ia à loja buscar o par e enviava. Ries lista dez tipos de pivot; os que aparecem acima são os mais citados.</p><p><b>Erros comuns:</b> chamar de MVP a versão 1.0 cheia de bugs; \"MVP\" que leva seis meses para ficar pronto; MVP sem hipótese nem métrica, que não ensina nada; pivotar a cada semana, sem dar tempo de o teste gerar dados.</p>",
          k: ["Tipos de MVP: landing page / fumaça, concierge (feito manualmente), Mágico de Oz (parece automático, é manual), vídeo, protótipo clicável.",
              "Tipos de pivot: zoom-in, zoom-out, segmento de cliente, necessidade do cliente, canal, modelo de receita, tecnologia.",
              "Decisão pivotar-ou-perseverar deve ter data marcada."] },
        { t: "Empreendedorismo",
          c: "<p>Criar negócios novos com recursos limitados. Ferramentas: <b>Lean Canvas</b> (Ash Maurya) e <b>Customer Development</b> (Steve Blank): descoberta → validação → criação → estruturação da empresa.</p><p><b>Exemplo de unit economics:</b> assinatura de R$ 100/mês com margem bruta de 70% e churn de 5% ao mês. LTV simplificado = (100 × 0,7) ÷ 0,05 = R$ 1.400. Com CAC de R$ 400, a razão LTV/CAC é 3,5 e o payback do CAC é 400 ÷ 70 ≈ 6 meses. David Skok indica como referência para SaaS LTV/CAC acima de 3 e payback abaixo de 12 meses.</p><p><b>Product-market fit:</b> o teste de Sean Ellis pergunta \"como você se sentiria se não pudesse mais usar o produto?\". Quando 40% ou mais respondem \"muito desapontado\", o produto costuma ter encontrado seu mercado.</p><p><b>Erros comuns:</b> investir pesado em aquisição antes do product-market fit; calcular o LTV com a receita, e não com a margem; esconder o churn dentro do crescimento total.</p>",
          k: ["Lean Canvas: problema, segmento, proposta de valor única, solução, canais, receitas, custos, métricas-chave, vantagem injusta.",
              "Product-market fit como marco central.",
              "Unit economics: CAC, LTV, churn, payback."] },
        { t: "Intraempreendedorismo",
          c: "<p>Empreender dentro de uma empresa estabelecida. Vantagens: marca, clientes, capital. Desafios: burocracia, aversão a risco, métricas do core aplicadas a iniciativas novas.</p><p><b>Na prática:</b> O'Reilly e Tushman (HBR, 2004) chamam de <b>organização ambidestra</b> a empresa que separa as unidades que buscam o novo das que operam o core, com processos e métricas próprios, mas integradas no topo pela liderança. Em <i>The Startup Way</i>, Ries descreve o <b>financiamento por etapas</b>: o time recebe verba para um ciclo, apresenta o que aprendeu e só então recebe a próxima parcela, como numa rodada de investimento.</p><p><b>Exemplo:</b> um squad de inovação recebe 3 meses para validar um produto de crédito para clientes PJ. No fim, apresenta os resultados dos experimentos a um comitê, que decide entre dar mais verba, pivotar ou encerrar.</p><p><b>Erros comuns:</b> o que Steve Blank chama de <b>teatro da inovação</b> (hackathons e laboratórios que não levam nada a produção); exigir do projeto novo o mesmo processo de aprovação do core; não ter caminho definido para integrar ao negócio o que deu certo.</p>",
          k: ["Estruturas: squads de inovação, hackathons, venture builders, corporate venture capital, spin-offs.",
              "Governança leve e orçamento por etapas (metered funding).",
              "Proteja a iniciativa das métricas do negócio principal enquanto ainda está validando."] }
      ],
      pratica: "<p>Preencha um Lean Canvas para uma ideia de produto interno da sua empresa. Liste as três hipóteses mais arriscadas e desenhe um MVP diferente para testar cada uma, com métrica e critério de sucesso.</p>",
      perguntas: [
        ["O que é um MVP concierge?", "Um MVP em que o serviço é entregue manualmente, de forma assumida, para validar se o cliente quer a solução antes de automatizar."],
        ["Qual a diferença entre métrica de vaidade e métrica acionável?", "Vaidade só cresce e não orienta decisão (ex.: total de cadastros); acionável mostra causa e efeito e orienta decisão (ex.: conversão por coorte após uma mudança)."],
        ["O que caracteriza uma inovação disruptiva?", "Começa atendendo um mercado de baixo valor ou novo com uma solução mais simples e barata e depois avança até o mercado principal."],
        ["Quais as três regras do The Mom Test?", "Fale da vida da pessoa, não da sua ideia; pergunte sobre fatos concretos do passado, não sobre opiniões ou o futuro; fale menos e escute mais."],
        ["Como calcular um LTV simplificado e a razão LTV/CAC?", "LTV ≈ receita mensal × margem bruta ÷ churn mensal. Divida pelo CAC; como referência para SaaS, a razão deve ficar acima de 3."],
        ["O que é o teste de product-market fit de Sean Ellis?", "Perguntar aos usuários como se sentiriam sem o produto. Se 40% ou mais respondem \"muito desapontado\", há sinal de product-market fit."],
        ["O que é uma organização ambidestra?", "A que explora o negócio atual e ao mesmo tempo busca o novo, com unidades separadas e processos próprios, integradas pela liderança."],
        ["Situação: o \"MVP\" do time está há 5 meses em desenvolvimento e nenhum usuário viu nada. O que você propõe?", "Parar e voltar às hipóteses. Escolha a mais arriscada e teste em dias ou semanas com um MVP barato (landing page, concierge, protótipo), com métrica e critério definidos antes. Marque a data da decisão de pivotar ou perseverar."]
      ],
      aprofundamento: [
        ["Udacity — How to Build a Startup (Steve Blank)", "https://www.udacity.com/course/how-to-build-a-startup--ep245", "curso gratuito do criador do Customer Development: Business Model Canvas e validação com clientes. Comece por aqui."],
        ["PUCRS Online — Empreendedorismo e Novos Modelos de Negócios", "https://online.pucrs.br/formacao-gratuita/empreendedorismo-e-novos-modelos-de-negocios", "curso gratuito em português (10 h, com certificado): Lean Startup, MVP e Lean Canvas."],
        ["Y Combinator — Startup School", "https://www.startupschool.org/", "curso gratuito da YC: ideias, validação, métricas e pitch (~7 semanas)."],
        ["Sebrae — Lean Startup e MVP", "https://sebrae.com.br/sites/PortalSebrae/artigos/artigoshome/entenda-o-que-e-lean-startup,03ebb2a178c83410VgnVCM1000003b74010aRCRD", "artigo em português com os conceitos básicos."],
        ["Sebrae PR — trilha \"Como fazer um Canvas\"", "https://sebraepr.com.br/trilhas/trilha/como-fazer-um-canvas", "curso curto e gratuito, com vídeos e PDFs."],
        ["Sebrae Canvas — ferramenta online", "https://canvas-apps.pr.sebrae.com.br/", "monte seu modelo de negócios de graça."],
        ["Steve Blank — blog", "https://steveblank.com/", "artigos gratuitos sobre Customer Development e inovação corporativa (intraempreendedorismo)."],
        ["Paul Graham — \"Do Things That Don't Scale\"", "https://paulgraham.com/ds.html", "ensaio clássico sobre MVPs manuais (concierge)."]
      ],
      referencias: [
        ["Ries, E. <i>A Startup Enxuta</i> (The Lean Startup, 2011)", "https://theleanstartup.com/principles"],
        ["Maurya, A. <i>Running Lean</i> — Lean Canvas", "https://leanstack.com/lean-canvas"],
        ["Blank, S. <i>The Four Steps to the Epiphany</i> — Customer Development", "https://steveblank.com/"],
        ["Fitzpatrick, R. <i>The Mom Test</i> (2013)", "https://www.momtestbook.com/"],
        ["Christensen, C. <i>O Dilema da Inovação</i> (1997)", ""],
        ["Christensen, C.; Raynor, M.; McDonald, R. \"What Is Disruptive Innovation?\" — HBR (2015)", "https://hbr.org/2015/12/what-is-disruptive-innovation"],
        ["Baghai, M.; Coley, S.; White, D. <i>The Alchemy of Growth</i> (1999) — 3 Horizontes (McKinsey)", ""],
        ["Nagji, B.; Tuff, G. \"Managing Your Innovation Portfolio\" — HBR (2012)", "https://hbr.org/2012/05/managing-your-innovation-portfolio"],
        ["O'Reilly, C.; Tushman, M. \"The Ambidextrous Organization\" — HBR (2004)", "https://hbr.org/2004/04/the-ambidextrous-organization"],
        ["Ries, E. <i>The Startup Way</i> (2017) — financiamento por etapas", ""],
        ["Skok, D. \"SaaS Metrics 2.0\" — For Entrepreneurs", "https://www.forentrepreneurs.com/saas-metrics-2/"],
        ["Vohra, R. \"How Superhuman Built an Engine to Find Product/Market Fit\" — First Round Review (teste de Sean Ellis)", "https://review.firstround.com/how-superhuman-built-an-engine-to-find-product-market-fit/"]
      ]
    }
  ],
  challenge: {
    intro: "Sugestão de projeto para praticar a fase (inspirado no Tech Challenge): escolha um problema real de uma empresa (pode ser fictícia) e construa a base estratégica de um produto digital.",
    entregas: ["Pesquisa com usuários e mapa de empatia / personas.", "Service Blueprint ou jornada do cliente.", "Lean Canvas e Product Vision Board.", "Hipóteses priorizadas e um MVP com métricas de validação.", "Um pitch de 5 minutos explicando problema, solução e próximos passos."]
  }
});
