window.CURSO.push({
  n: 5,
  periodo: "Meses 9 e 10",
  titulo: "Cloud, Pessoas, Cultura e Liderança Avançada",
  descricao: "Estratégia de nuvem e custos, gestão de resultados e retenção, observabilidade, cultura, gestão da mudança e as habilidades avançadas de liderança.",
  disciplinas: [
    {
      titulo: "Estratégia, Cloud & FinOps",
      resumo: "Escolher o modelo de nuvem certo, arquitetar bem e controlar o custo como uma variável de engenharia.",
      topicos: [
        { t: "Single Cloud, Multi Cloud & Hybrid Cloud",
          c: "<p><b>Single cloud</b>: um provedor — mais simples, aproveita serviços gerenciados e descontos. <b>Multi cloud</b>: vários provedores públicos — reduz dependência ou aproveita o melhor de cada um, com mais complexidade. <b>Hybrid cloud</b>: nuvem pública + infraestrutura privada/on-premises integradas.</p><p><b>Exemplo de decisão:</b> uma fintech começa em um único provedor, usando banco gerenciado, filas e funções serverless, porque velocidade importa mais que portabilidade. O mainframe do parceiro bancário continua on-premises, conectado por link dedicado (híbrido). Um segundo provedor entra só para um caso específico: recuperação de desastre exigida pela área de risco.</p><p><b>Setor financeiro no Brasil:</b> a Resolução CMN nº 4.893/2021 exige que as instituições autorizadas pelo Banco Central (com algumas exceções, como instituições de pagamento) tenham política de segurança cibernética e cumpram requisitos ao contratar nuvem: comunicar a contratação ao BC, garantir acesso aos dados e direito de auditoria, e ter plano de continuidade e de saída. Esses requisitos pesam na escolha do modelo.</p><p><b>Erros comuns:</b> multi cloud \"por via das dúvidas\", pagando a complexidade sem ter o benefício; rehost de tudo e esperar economia (máquinas grandes ligadas 24 horas custam mais na nuvem); não ter plano de saída de um provedor.</p>",
          k: ["Modelos de serviço: IaaS, PaaS, SaaS (e FaaS/serverless).",
              "Estratégias de migração — os 7 Rs (AWS): Retire, Retain, Rehost, Relocate, Replatform, Repurchase, Refactor.",
              "Multi cloud \"por padrão\" costuma nivelar tudo pelo mínimo comum; tenha um motivo claro (regulação, resiliência, capacidade específica).",
              "Modelo de responsabilidade compartilhada em segurança."] },
        { t: "Well-Architected Framework",
          c: "<p>Conjunto de boas práticas dos provedores (AWS, Azure, Google Cloud). O da AWS tem 6 pilares: <b>Excelência Operacional</b>, <b>Segurança</b>, <b>Confiabilidade</b>, <b>Eficiência de Performance</b>, <b>Otimização de Custos</b> e <b>Sustentabilidade</b>.</p><p><b>Como é uma revisão:</b> para cada carga crítica, o time responde às perguntas de cada pilar (por exemplo, \"como você protege os dados em repouso?\", \"como você testa a recuperação?\"). A ferramenta aponta riscos altos e médios, e o time monta um plano de melhoria priorizado. A revisão deve ser repetida depois de mudanças grandes, e não feita uma vez só.</p><p><b>Exemplo de trade-off:</b> rodar o banco em várias zonas de disponibilidade na mesma região aumenta a confiabilidade a um custo moderado. Rodar em duas regiões protege contra a falha de uma região inteira, mas pode dobrar o custo e exige lidar com replicação e consistência. A escolha depende do SLO e do custo da indisponibilidade para o negócio, não do \"quanto mais, melhor\".</p><p><b>Erros comuns:</b> tratar a revisão como auditoria para passar, e não como ferramenta do time; otimizar um pilar ignorando os outros (reduzir custo cortando backups, por exemplo).</p>",
          k: ["Faça revisões periódicas (Well-Architected Reviews) das cargas críticas.",
              "Trade-offs são explícitos: mais confiabilidade geralmente custa mais.",
              "Azure e Google têm frameworks equivalentes com pilares semelhantes."] },
        { t: "FinOps by Design",
          c: "<p><b>FinOps</b> é a prática cultural e operacional que dá responsabilidade financeira ao uso variável da nuvem, unindo engenharia, finanças e negócio. A FinOps Foundation define as fases <b>Informar → Otimizar → Operar</b>. <i>By design</i> significa considerar o custo já na arquitetura, e não só depois da fatura.</p><p><b>Os seis princípios da FinOps Foundation:</b> os times precisam colaborar; o valor de negócio guia as decisões de tecnologia; todos são donos do próprio uso; os dados de custo devem ser acessíveis, atualizados e precisos; o FinOps deve ser habilitado por uma função central; e deve-se aproveitar o modelo de custo variável da nuvem.</p><p><b>Na prática:</b> uma política de tags obrigatórias (<code>produto</code>, <code>time</code>, <code>ambiente</code>), validada no pipeline de infraestrutura como código, permite dizer quanto cada produto custa. A ordem das otimizações importa: primeiro elimine o desperdício e ajuste o tamanho dos recursos (rightsizing), depois compre compromissos (reservas, savings plans). Reservar antes de ajustar é comprar desconto para capacidade que você não precisa. O <b>FOCUS</b>, especificação aberta da FinOps Foundation, padroniza os dados de cobrança de diferentes provedores de nuvem, SaaS e IA.</p><p><b>Erros comuns:</b> tratar FinOps como \"cortar custos\" (o objetivo é gastar bem, e às vezes isso significa gastar mais onde há retorno); a fatura chegar só para finanças, sem os engenheiros verem; ambientes de teste ligados no fim de semana.</p>",
          k: ["Tagging e alocação de custos por time/produto (showback/chargeback).",
              "Otimização de taxa: instâncias reservadas, savings plans, spot.",
              "Otimização de uso: rightsizing, desligar ambientes ociosos, autoscaling, camadas de armazenamento.",
              "Custo como requisito não funcional e métrica de engenharia."] },
        { t: "Cloud Usage and Cost Modeling",
          c: "<p>Modelar o custo antes de construir: estimar o uso (requisições, armazenamento, transferência de dados, horas de computação) e transformar em custo com as calculadoras dos provedores.</p><p><b>Exemplo de custo unitário</b> (números ilustrativos): a plataforma custa R$ 60 mil por mês e processa 200 mil pedidos, ou R$ 0,30 por pedido. Se o ticket médio é R$ 80, a nuvem representa menos de 0,4% da receita por pedido. O número absoluto da fatura pode subir com o crescimento; o que o time acompanha é se o custo por pedido cai ou, pelo menos, se mantém.</p><p><b>Custos escondidos:</b> um serviço que envia muitos dados para a internet ou entre regiões paga transferência (egress) por GB, o que pode superar o custo da computação. Logs de depuração ligados em produção e retidos por um ano também podem pesar mais que o próprio banco. Na modelagem, inclua esses itens desde o início.</p><p><b>Erros comuns:</b> estimar só a computação; não configurar budgets e alertas de anomalia (e descobrir o problema na fatura do mês seguinte); não revisar a estimativa com o uso real depois do lançamento.</p>",
          k: ["<b>Unit economics:</b> custo por cliente, por transação, por pedido — liga custo de nuvem a valor de negócio.",
              "Cuidado com custos escondidos: transferência de dados (egress), logs, NAT, chamadas a APIs gerenciadas.",
              "Budgets e alertas de anomalia de custo.",
              "Previsão (forecast) baseada no crescimento do negócio."] }
      ],
      pratica: "<p>Estime o custo mensal de uma arquitetura simples (API em contêineres, banco gerenciado, armazenamento de objetos, CDN) usando a calculadora de um provedor. Calcule o custo por usuário ativo e proponha três otimizações.</p>",
      perguntas: [
        ["Quais os 6 pilares do AWS Well-Architected?", "Excelência operacional, segurança, confiabilidade, eficiência de performance, otimização de custos e sustentabilidade."],
        ["Quais as três fases do FinOps?", "Informar, Otimizar e Operar."],
        ["Qual a diferença entre rehost e refactor?", "Rehost (lift-and-shift) move a aplicação sem mudanças; refactor reescreve/rearquiteta para aproveitar recursos nativos da nuvem."],
        ["Por que fazer rightsizing antes de comprar instâncias reservadas?", "Porque reservar antes de ajustar o tamanho significa comprometer-se, por um ou três anos, a pagar por capacidade que você não usa."],
        ["Cite três princípios do FinOps.", "Por exemplo: os times precisam colaborar; o valor de negócio guia as decisões; todos são donos do próprio uso. Os outros são: dados acessíveis, atualizados e precisos; função central habilitadora; e aproveitar o custo variável da nuvem."],
        ["O que é o FOCUS?", "Uma especificação aberta da FinOps Foundation que padroniza os dados de cobrança de provedores de nuvem, SaaS e IA."],
        ["Por que acompanhar o custo unitário, e não só o total da fatura?", "Porque o total cresce com o negócio. O custo por pedido, cliente ou transação mostra se a eficiência está melhorando ou piorando."],
        ["Situação: a fatura de nuvem subiu 40% em um mês, e o negócio cresceu 5%. O que você faz?", "Quebre o custo por serviço, conta e tag para achar a origem (egress, logs, ambiente esquecido, autoscaling sem limite). Aja no pontual, depois implante budgets, alertas de anomalia e tags obrigatórias, e combine com os times um custo unitário-alvo."]
      ],
      aprofundamento: [
        ["FinOps Foundation — Introduction to FinOps", "https://learn.finops.org/introduction-to-finops", "curso introdutório gratuito. Comece por aqui."],
        ["AWS Skill Builder — Cloud Practitioner Essentials", "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials", "curso gratuito (~8 h): conceitos de nuvem, segurança, arquitetura e preços."],
        ["Microsoft Learn — Describe cloud concepts", "https://learn.microsoft.com/en-us/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/", "trilha gratuita de fundamentos de nuvem (AZ-900)."],
        ["Microsoft Learn — Get started with FinOps", "https://learn.microsoft.com/en-us/training/modules/get-started-with-finops/", "módulo gratuito de FinOps."],
        ["AWS — Well-Architected Framework", "https://aws.amazon.com/architecture/well-architected/", "documentação completa e gratuita dos 6 pilares."]
      ],
      referencias: [
        ["NIST SP 800-145 — The NIST Definition of Cloud Computing", "https://csrc.nist.gov/pubs/sp/800/145/final"],
        ["AWS — Well-Architected Framework", "https://aws.amazon.com/architecture/well-architected/"],
        ["Microsoft — Azure Well-Architected Framework", "https://learn.microsoft.com/en-us/azure/well-architected/"],
        ["Google Cloud — Architecture Framework", "https://cloud.google.com/architecture/framework"],
        ["AWS — Migration strategies (7 Rs)", "https://docs.aws.amazon.com/prescriptive-guidance/latest/large-migration-guide/migration-strategies.html"],
        ["FinOps Foundation — FinOps Framework", "https://www.finops.org/framework/"],
        ["Storment, J. R.; Fuller, M. <i>Cloud FinOps</i> (2ª ed., O'Reilly, 2023)", ""],
        ["AWS — Shared Responsibility Model", "https://aws.amazon.com/compliance/shared-responsibility-model/"],
        ["FinOps Foundation — FinOps Principles", "https://www.finops.org/framework/principles/"],
        ["FinOps Foundation — FOCUS (FinOps Open Cost and Usage Specification)", "https://focus.finops.org/"],
        ["Resolução CMN nº 4.893/2021 — segurança cibernética e contratação de nuvem por instituições financeiras", ""]
      ]
    },
    {
      titulo: "Gestão das Equipes e Retenção",
      resumo: "Gerir por resultados, desenvolver pessoas com conversas frequentes e criar um ambiente de autonomia e aprendizado que faça as pessoas quererem ficar.",
      topicos: [
        { t: "Gestão de Resultados",
          c: "<p>Foco em <b>resultados</b> (outcomes) em vez de atividades ou horas. Defina expectativas claras, acompanhe com frequência e reconheça o impacto.</p><p><b>Exemplo:</b> <b>output</b>: \"lançamos o novo onboarding\". <b>Outcome</b>: \"a ativação no primeiro mês subiu de 40% para 55%\". <b>Impact</b>: \"a receita recorrente cresceu 8% no semestre\". Um time pode entregar muitos outputs sem mover nenhum outcome; por isso, a conversa de resultados começa pelo outcome.</p><p><b>Na avaliação:</b> vieses comuns são o de <b>recência</b> (lembrar só dos últimos meses), o <b>efeito halo</b> (uma qualidade contamina a nota toda) e o de <b>semelhança</b> (avaliar melhor quem é parecido com o gestor). Anotações ao longo do ciclo, critérios escritos por nível e calibração entre gestores reduzem esses efeitos.</p><p><b>Erros comuns:</b> avaliar pelo número de horas ou pela disponibilidade no chat; surpresas na avaliação (se a pessoa só descobre ali que estava abaixo do esperado, o problema foi o acompanhamento); metas individuais que competem com as do time.</p>",
          k: ["Output (o que foi entregue) × outcome (mudança de comportamento/resultado) × impact (resultado de negócio).",
              "Ciclo: planejar metas → acompanhar → avaliar → desenvolver.",
              "Avaliação de desempenho: combine o quê (resultados) e o como (comportamentos).",
              "Calibração entre gestores para reduzir viés."] },
        { t: "Do BSC ao OKR",
          c: "<p><b>Balanced Scorecard</b> (Kaplan & Norton, 1992): traduz a estratégia em indicadores em 4 perspectivas — <b>Financeira</b>, <b>Clientes</b>, <b>Processos internos</b> e <b>Aprendizado e crescimento</b> — ligadas por um mapa estratégico. <b>OKR</b> (Andy Grove na Intel, popularizado por John Doerr no Google): <b>Objetivo</b> qualitativo e inspirador + 2 a 5 <b>Key Results</b> mensuráveis, em ciclos curtos (normalmente trimestrais).</p><p><b>Exemplo de OKR:</b> <b>Objetivo:</b> tornar o checkout a parte mais confiável da experiência. <b>KR1:</b> reduzir a taxa de erro no pagamento de 2,1% para 0,5%. <b>KR2:</b> subir a conversão do checkout de 62% para 68%. <b>KR3:</b> zerar incidentes de severidade 1 no checkout no trimestre. As iniciativas (migrar o gateway, refazer a validação de cartão) ficam fora do OKR: são apostas para mover os KRs.</p><p>Doerr acrescenta aos OKRs as <b>CFRs</b>: Conversas, Feedback e Reconhecimento contínuos, que substituem a revisão anual como principal ferramenta de acompanhamento. No BSC, o <b>mapa estratégico</b> liga as perspectivas por causa e efeito: capacitar o time (aprendizado) melhora a entrega (processos), que melhora a experiência (clientes), que aumenta a receita (financeira).</p><p><b>Erros comuns:</b> dez objetivos por time; KRs que são lista de tarefas; OKRs impostos de cima para baixo sem conversa; definir e só olhar de novo no fim do trimestre.</p>",
          k: ["BSC é mais estável e de longo prazo; OKR é mais ágil e focado em mudança.",
              "OKRs ambiciosos (\"moonshots\") × comprometidos; atingir 60–70% de um ambicioso é bom.",
              "KR é resultado, não tarefa: \"reduzir churn de 5% para 3%\", não \"lançar feature X\".",
              "Não amarre OKR diretamente a bônus — incentiva metas conservadoras."] },
        { t: "Técnicas no 1:1 e Feedbacks",
          c: "<p>O <b>1:1</b> é a reunião <i>da pessoa liderada</i>, não um status report. Frequência semanal ou quinzenal, pauta compartilhada. Feedback deve ser frequente, específico e oportuno.</p><p><b>Exemplo de pauta de 1:1</b> (a pessoa traz os temas, o líder completa): como você está? (a pessoa, não o projeto); o que está travando; um tema de carreira ou aprendizado; feedback nas duas direções (\"o que eu poderia fazer diferente?\"); revisão dos combinados da última conversa. Grove já defendia, em <i>High Output Management</i>, que o 1:1 é a reunião do liderado e que a pauta deve vir dele.</p><p>Kim Scott organiza o feedback em dois eixos, e os quadrantes mostram os erros: <b>Radical Candor</b> (se importa e desafia), <b>agressividade ofensiva</b> (desafia sem se importar), <b>empatia ruinosa</b> (se importa, mas não diz o que precisa ser dito) e <b>falsidade manipuladora</b> (nem se importa nem desafia). O mais comum entre líderes novos é a empatia ruinosa: evitar a conversa difícil \"para não magoar\".</p><p><b>Erros comuns:</b> cancelar o 1:1 sempre que surge algo urgente (a mensagem é \"você não é prioridade\"); usar o 1:1 como status report; guardar feedback para a avaliação semestral.</p>",
          k: ["Modelo <b>SBI</b> (Center for Creative Leadership): Situação, Comportamento (Behavior), Impacto.",
              "<b>Radical Candor</b> (Kim Scott): importar-se pessoalmente + desafiar diretamente.",
              "Perguntas úteis no 1:1: \"O que está te travando?\", \"O que você gostaria de aprender?\", \"Como posso te ajudar mais?\"",
              "Feedback positivo também precisa ser específico.",
              "Anote e acompanhe os combinados."] },
        { t: "Autonomia e empowerment nas equipes",
          c: "<p>Autonomia sem alinhamento vira caos; alinhamento sem autonomia vira burocracia. O objetivo é <b>alto alinhamento com alta autonomia</b>: o líder define o <i>quê</i> e o <i>porquê</i>, o time decide o <i>como</i>.</p><p><b>Na prática:</b> Marquet, comandante de submarino, trocou as ordens pela linguagem de intenção. Em vez de o oficial perguntar \"posso submergir?\", ele diz \"pretendo submergir; as verificações estão feitas e a área está livre\". O comandante só precisa dizer \"muito bem\". Ao descrever o que vai fazer e por quê, a pessoa mostra que tem o contexto e assume a decisão. No time, isso vira \"pretendo fazer rollback da versão 3.2 porque a taxa de erro passou do SLO\", em vez de \"o que eu faço?\".</p><p><b>Exemplo de alinhamento:</b> o líder compartilha o OKR, os limites (orçamento, prazo regulatório, padrões de segurança) e os dados. O time decide a solução e o plano, e combina quando e como vai informar o progresso.</p><p><b>Erros comuns:</b> dar autonomia e depois desfazer as decisões do time; autonomia sem contexto (o time decide no escuro); \"empoderar\" como forma de transferir responsabilidade sem transferir recursos.</p>",
          k: ["Delegation Poker / 7 níveis de delegação (Management 3.0): contar, vender, consultar, concordar, aconselhar, perguntar, delegar.",
              "Intent-based leadership (David Marquet): \"eu pretendo…\" em vez de \"posso…?\".",
              "Contexto, não controle (cultura Netflix)."] },
        { t: "Cultura do aprendizado",
          c: "<p>Organizações que aprendem (Peter Senge) tratam erros como fonte de conhecimento e investem em desenvolvimento contínuo. A <b>mentalidade de crescimento</b> (Carol Dweck) acredita que habilidades se desenvolvem com esforço.</p><p><b>As cinco disciplinas de Senge:</b> domínio pessoal, modelos mentais, visão compartilhada, aprendizagem em equipe e pensamento sistêmico, a \"quinta disciplina\", que integra as outras. <b>Nuance sobre mindset:</b> duas meta-análises de Sisk et al. (2018) encontraram efeitos, em média, fracos das intervenções de mentalidade de crescimento sobre o desempenho acadêmico, maiores em alguns grupos. A ideia é útil como postura do líder, mas não é solução mágica.</p><p><b>Stay interview:</b> conversas com quem <i>fica</i>, para descobrir o que manteria a pessoa e o que a faria sair antes que ela saia. Perguntas típicas: \"o que te faz continuar aqui?\", \"o que te faria pensar em sair?\", \"o que você gostaria de aprender que não está conseguindo?\".</p><p><b>Erros comuns:</b> PDI preenchido para cumprir o RH e nunca revisto; carreira que só cresce virando gestor, o que tira bons técnicos de onde são mais úteis; cortar o tempo de estudo sempre que o prazo aperta.</p>",
          k: ["Planos de desenvolvimento individual (PDI) e trilhas de carreira em Y (técnica e gestão).",
              "Tempo reservado para estudo, guildas, tech talks, pair/mob programming.",
              "Retenção: pessoas saem de gestores, de falta de crescimento e de falta de propósito — monitore com stay interviews, não só exit interviews.",
              "eNPS e pesquisas de clima para medir engajamento."] }
      ],
      pratica: "<p>Escreva um OKR para o seu time no próximo trimestre (1 objetivo, 3 KRs). Depois, prepare uma pauta de 1:1 e um feedback no formato SBI para uma situação real.</p>",
      perguntas: [
        ["Quais as 4 perspectivas do BSC?", "Financeira, Clientes, Processos Internos e Aprendizado e Crescimento."],
        ["O que caracteriza um bom Key Result?", "É mensurável, tem um valor-alvo e prazo, e descreve um resultado, não uma tarefa."],
        ["O que significa SBI?", "Situação, Comportamento (Behavior) e Impacto — modelo para dar feedback específico e não julgador."],
        ["Diferencie output, outcome e impact com um exemplo.", "Output: \"lançamos o novo onboarding\". Outcome: \"a ativação subiu de 40% para 55%\". Impact: \"a receita recorrente cresceu 8%\"."],
        ["Quais os quatro quadrantes do Radical Candor?", "Radical Candor, agressividade ofensiva, empatia ruinosa e falsidade manipuladora."],
        ["O que são as CFRs de John Doerr?", "Conversas, Feedback e Reconhecimento contínuos, que complementam os OKRs."],
        ["Qual a quinta disciplina de Senge e por que ela é central?", "O pensamento sistêmico, porque integra as outras quatro: domínio pessoal, modelos mentais, visão compartilhada e aprendizagem em equipe."],
        ["Situação: uma das melhores pessoas do time pede demissão dizendo que \"não aprende mais nada\". O que você aprende e o que muda?", "Faltou crescimento, e o sinal não foi percebido. Faça stay interviews com o resto do time, revise os PDIs, crie desafios e rodízio de responsabilidades, garanta tempo protegido para aprendizado e confirme se existe trilha técnica além da gestão. Na saída, pergunte o que teria feito a pessoa ficar."]
      ],
      aprofundamento: [
        ["Google re:Work — Set goals with OKRs", "https://rework.withgoogle.com/intl/en/guides/set-goals-with-okrs", "o guia do Google para OKRs. Comece por aqui."],
        ["GitLab Handbook — 1-1", "https://handbook.gitlab.com/handbook/leadership/1-1/", "como conduzir 1:1s, com modelo de pauta."],
        ["GitLab Handbook — Underperformance", "https://handbook.gitlab.com/handbook/leadership/underperformance/", "como lidar com baixo desempenho (modelo habilidade × vontade)."],
        ["What Matters — recursos de OKR", "https://www.whatmatters.com/", "artigos e exemplos de OKRs do John Doerr."],
        ["Management 3.0 — Delegation Poker", "https://management30.com/practice/delegation-poker/", "prática gratuita para combinar níveis de autonomia."]
      ],
      referencias: [
        ["Kaplan, R.; Norton, D. \"The Balanced Scorecard — Measures That Drive Performance\" — HBR (1992)", "https://hbr.org/1992/01/the-balanced-scorecard-measures-that-drive-performance-2"],
        ["Doerr, J. <i>Avalie o que Importa</i> (Measure What Matters, 2018)", "https://www.whatmatters.com/"],
        ["Grove, A. <i>Gestão de Alta Performance</i> (High Output Management, 1983)", ""],
        ["Scott, K. <i>Empatia Assertiva</i> (Radical Candor, 2017)", "https://www.radicalcandor.com/"],
        ["Center for Creative Leadership — SBI Feedback Model", "https://www.ccl.org/articles/leading-effectively-articles/closing-the-gap-between-intent-vs-impact-sbii/"],
        ["Management 3.0 — Delegation Poker", "https://management30.com/practice/delegation-poker/"],
        ["Marquet, D. <i>Turn the Ship Around!</i> (2012)", ""],
        ["Senge, P. <i>A Quinta Disciplina</i> (1990)", ""],
        ["Dweck, C. <i>Mindset</i> (2006)", ""],
        ["Netflix — Culture memo", "https://jobs.netflix.com/culture"],
        ["Sisk, V. et al. \"To What Extent and Under Which Circumstances Are Growth Mind-Sets Important to Academic Achievement? Two Meta-Analyses\" — Psychological Science (2018)", "https://journals.sagepub.com/doi/abs/10.1177/0956797617739704"]
      ]
    },
    {
      titulo: "Observability",
      resumo: "Observabilidade é conseguir entender o estado interno de um sistema a partir do que ele emite — e fazer perguntas novas sem precisar publicar código novo.",
      topicos: [
        { t: "Monitoramento de produto",
          c: "<p>Acompanhar como os usuários usam o produto e se ele entrega valor: funis, retenção, ativação, adoção de features. Ferramentas de product analytics (ex.: Amplitude, Mixpanel) e experimentação.</p><p><b>Na prática:</b> o HEART vem com o processo <b>Goals → Signals → Metrics</b>: primeiro o objetivo (\"usuários concluem o cadastro sem ajuda\"), depois o sinal que indica sucesso (\"cadastro finalizado na primeira sessão\"), e só então a métrica (\"% de cadastros concluídos em até 10 minutos\"). Isso evita instrumentar tudo sem saber qual pergunta se quer responder.</p><p>Os <b>Core Web Vitals</b> do Google medem a experiência real no navegador: <b>LCP</b> (carregamento, bom até 2,5 s), <b>INP</b> (resposta à interação, bom até 200 ms) e <b>CLS</b> (estabilidade visual, bom até 0,1), medidos no percentil 75 dos acessos.</p><p><b>Erros comuns:</b> métricas de vaidade (pageviews, cadastros sem ativação); eventos sem padrão de nomenclatura, que ninguém consegue consultar; coletar dados pessoais no analytics sem base legal (veja LGPD, na Fase 3).</p>",
          k: ["Framework HEART (Google): Happiness, Engagement, Adoption, Retention, Task success.",
              "Métricas AARRR (pirata): Aquisição, Ativação, Retenção, Receita, Recomendação.",
              "Monitoramento de experiência real do usuário (RUM) e Core Web Vitals."] },
        { t: "Monitoramento de suporte e manutenção (KPI, SLA)",
          c: "<p><b>SLI</b> (indicador: ex. % de requisições com sucesso em menos de 300 ms) → <b>SLO</b> (objetivo interno: ex. 99,9% em 30 dias) → <b>SLA</b> (acordo contratual com o cliente, com penalidades). O <b>error budget</b> é o quanto você pode falhar dentro do SLO.</p><p><b>Na prática:</b> o SLO interno deve ser mais rigoroso que o SLA. Se o contrato promete 99,5%, o time mira 99,9%, para ter margem de reação antes da multa. O SLI deve medir o que o usuário sente (requisições com sucesso, latência no percentil 99), e não CPU ou memória.</p><p>Na gestão de incidentes, papéis claros evitam que todos tentem resolver ao mesmo tempo: o <b>comandante do incidente</b> coordena e decide, alguém cuida da <b>comunicação</b> com clientes e liderança, e os especialistas cuidam da <b>operação</b>. Depois vem o post-mortem sem culpa.</p><p><b>Erros comuns:</b> SLO de 100%; SLA assinado pela área comercial sem consultar engenharia; olhar só o MTTR médio. Um relatório do Google sobre métricas de incidentes (Davidovič, 2021) mostra que a distribuição da duração dos incidentes é tão irregular que médias como o MTTR enganam: prefira percentis e a análise de cada caso.</p>",
          k: ["99,9% ao mês ≈ 43 min de indisponibilidade; 99,99% ≈ 4,3 min.",
              "KPIs de suporte: MTTA, MTTR, volume de incidentes, backlog de chamados, tempo de primeira resposta, reincidência.",
              "Error budget esgotado → prioriza confiabilidade sobre features.",
              "Gestão de incidentes com severidades, comandante do incidente e post-mortem."] },
        { t: "Alertas de Cloud e servidores",
          c: "<p>Alerte sobre <b>sintomas</b> que afetam usuários, não sobre cada causa possível. Métodos para escolher sinais: <b>4 Golden Signals</b> (latência, tráfego, erros, saturação), <b>RED</b> (Rate, Errors, Duration — para serviços) e <b>USE</b> (Utilization, Saturation, Errors — para recursos).</p><p><b>Exemplo:</b> \"disco em 90%\" é causa; \"latência p99 do checkout acima do SLO\" é sintoma. O primeiro vira ticket ou gráfico no dashboard; o segundo acorda alguém. Use RED para serviços (APIs, filas) e USE para recursos (CPU, disco, conexões de banco).</p><p><b>Burn rate</b> é a velocidade com que o error budget está sendo consumido: 1 significa gastar exatamente o orçamento no período do SLO. O SRE Workbook recomenda alertas de múltiplas janelas: <b>page</b> quando 2% do orçamento mensal somem em 1 hora (burn rate 14,4) ou 5% em 6 horas (6), e <b>ticket</b> quando 10% somem em 3 dias (1). Cada alerta também confere uma janela curta, para parar de disparar quando o problema já passou.</p><p><b>Erros comuns:</b> alertas com limites padrão da ferramenta; alerta sem dono nem runbook; plantão que recebe dezenas de alertas por noite e se acostuma a ignorar.</p>",
          k: ["Todo alerta deve ser acionável e ter um runbook.",
              "Alertas por queima de error budget (burn rate) reduzem ruído.",
              "Fadiga de alertas é um risco real — revise alertas que ninguém age.",
              "Separe o que acorda alguém (page) do que vira ticket."] },
        { t: "Ferramentas de Observability (Datadog, New Relic, Opsgenie)",
          c: "<p>Os três pilares da telemetria: <b>métricas</b>, <b>logs</b> e <b>traces</b> (rastreamento distribuído). O <b>OpenTelemetry</b> (CNCF) é o padrão aberto para instrumentar e coletar, evitando lock-in de fornecedor.</p><p><b>Na prática:</b> o OpenTelemetry tem APIs e SDKs por linguagem, o protocolo <b>OTLP</b> e o <b>Collector</b>, que recebe, processa e envia a telemetria para qualquer backend. Assim, trocar o Datadog por Grafana, ou o contrário, vira mudança de configuração, e não de código. O essencial é a <b>correlação</b>: o mesmo trace ID nos logs e nos spans permite ir do alerta à requisição exata que falhou.</p><p><i>Observability Engineering</i> (Majors e coautoras) defende eventos estruturados com <b>alta cardinalidade</b> (ID do usuário, do pedido, da versão). São eles que permitem responder perguntas novas, como \"só falha para clientes do plano X no app Android 5.2?\", sem publicar código novo.</p><p><b>Situação das ferramentas:</b> a Atlassian encerrou a venda do Opsgenie em 4 de junho de 2025, e o fim do suporte está marcado para 5 de abril de 2027. As funções de alerta e plantão estão migrando para o Jira Service Management e o Compass. Confira a situação atual antes de escolher uma ferramenta.</p><p><b>Erros comuns:</b> tratar métricas, logs e traces como três silos sem correlação; guardar tudo para sempre (defina retenção e amostragem, head ou tail); escolher ferramenta antes de definir SLOs.</p>",
          k: ["<b>Datadog</b> e <b>New Relic</b>: plataformas SaaS de observabilidade completa (APM, infraestrutura, logs, RUM).",
              "<b>Opsgenie</b> (Atlassian) e PagerDuty: gestão de plantão, escalonamento e roteamento de alertas.",
              "Stack open source: Prometheus + Grafana, Loki (logs), Tempo/Jaeger (traces).",
              "Custo de observabilidade cresce rápido — defina retenção e amostragem."] }
      ],
      pratica: "<p>Defina 3 SLIs e SLOs para o serviço mais crítico do seu produto, calcule o error budget mensal e escreva a política do que acontece quando ele acaba. Liste os alertas (page × ticket) e um runbook para um deles.</p>",
      perguntas: [
        ["Qual a diferença entre SLI, SLO e SLA?", "SLI é a medida; SLO é o objetivo interno para essa medida; SLA é o compromisso contratual com o cliente, com consequências."],
        ["Quais são os 4 Golden Signals?", "Latência, tráfego, erros e saturação."],
        ["Quais os três pilares da telemetria?", "Métricas, logs e traces."],
        ["Por que o SLO interno deve ser mais rigoroso que o SLA?", "Para dar margem de reação: o time percebe e corrige a degradação antes de violar o contrato e pagar penalidades."],
        ["O que é burn rate e por que alertar por ele?", "É a velocidade de consumo do error budget. Alertar por burn rate liga o alerta ao impacto real no SLO, o que reduz o ruído e diferencia problema urgente (page) de lento (ticket)."],
        ["Quando usar RED e quando usar USE?", "RED (Rate, Errors, Duration) para serviços que atendem requisições; USE (Utilization, Saturation, Errors) para recursos como CPU, disco e rede."],
        ["Quais são os Core Web Vitals e seus limites de \"bom\"?", "LCP até 2,5 s, INP até 200 ms e CLS até 0,1, no percentil 75."],
        ["Situação: o plantão recebe 40 alertas por noite e a maioria é ignorada. O que você faz?", "Levante os alertas das últimas semanas e remova ou rebaixe a ticket os que não levaram a nenhuma ação. Troque alertas de causa por alertas de sintoma ligados ao SLO (burn rate), exija dono e runbook para cada page e acompanhe o número de pages por plantão como métrica de saúde do time."]
      ],
      aprofundamento: [
        ["Linux Foundation — Getting Started with OpenTelemetry (LFS148)", "https://training.linuxfoundation.org/training/getting-started-with-opentelemetry-lfs148/", "curso gratuito (~10 h) com labs práticos."],
        ["Honeycomb — <i>Observability Engineering</i> (e-book)", "https://www.honeycomb.io/observability-engineering-oreilly-book", "livro da O'Reilly em PDF gratuito (requer cadastro). Comece por aqui."],
        ["Google — SRE Workbook: Implementing SLOs", "https://sre.google/workbook/implementing-slos/", "capítulo gratuito e prático sobre SLIs, SLOs e error budgets."],
        ["Atlassian — Incident Management Handbook", "https://www.atlassian.com/incident-management/handbook", "manual gratuito de gestão de incidentes e post-mortems."]
      ],
      referencias: [
        ["Google — <i>Site Reliability Engineering</i>, cap. \"Monitoring Distributed Systems\" (4 Golden Signals)", "https://sre.google/sre-book/monitoring-distributed-systems/"],
        ["Google — <i>The Site Reliability Workbook</i>, \"Implementing SLOs\" e \"Alerting on SLOs\"", "https://sre.google/workbook/implementing-slos/"],
        ["Gregg, B. — The USE Method", "https://www.brendangregg.com/usemethod.html"],
        ["Wilkie, T. — The RED Method (Grafana Labs)", "https://grafana.com/blog/2018/08/02/the-red-method-how-to-instrument-your-services/"],
        ["Majors, C.; Fong-Jones, L.; Miranda, G. <i>Observability Engineering</i> (O'Reilly, 2022)", ""],
        ["OpenTelemetry — documentação", "https://opentelemetry.io/docs/"],
        ["Rodden, K. et al. \"Measuring the User Experience on a Large Scale\" — framework HEART (Google, 2010)", "https://research.google/pubs/measuring-the-user-experience-on-a-large-scale-user-centered-metrics-for-web-applications/"],
        ["Datadog — documentação", "https://docs.datadoghq.com/"],
        ["New Relic — documentação", "https://docs.newrelic.com/"],
        ["Atlassian — Opsgenie e guia de gestão de incidentes", "https://www.atlassian.com/incident-management"],
        ["Atlassian — \"The Evolution of IT Operations and Opsgenie\" (anúncio do fim do Opsgenie, 2025)", "https://www.atlassian.com/blog/announcements/evolution-of-it-operations"],
        ["Google — <i>The Site Reliability Workbook</i>, \"Alerting on SLOs\" (burn rate)", "https://sre.google/workbook/alerting-on-slos/"],
        ["Google — web.dev: Web Vitals", "https://web.dev/articles/vitals"],
        ["Davidovič, Š. <i>Incident Metrics in SRE</i> (Google/O'Reilly, 2021)", ""]
      ]
    },
    {
      titulo: "Cultura Organizacional",
      resumo: "Cultura é o conjunto de comportamentos que a organização recompensa e tolera — e o líder tem papel direto em formá-la dentro do time.",
      topicos: [
        { t: "Implantando a cultura nos times",
          c: "<p>Edgar Schein descreve três níveis de cultura: <b>artefatos</b> (visíveis: rituais, espaço, ferramentas), <b>valores declarados</b> (o que a empresa diz) e <b>pressupostos básicos</b> (crenças inconscientes que realmente guiam o comportamento). Mudar cultura é agir no nível mais profundo.</p><p><b>Na prática:</b> os pressupostos aparecem quando o discurso e a ação não batem. A empresa pode declarar que \"errar faz parte\", mas, se quem derruba a produção é exposto em reunião, o pressuposto real é \"erro é punido\", e as pessoas passam a esconder problemas. Schein mostra que o líder transmite cultura principalmente pelo que <b>mede e controla</b>, por como <b>reage a crises</b>, pelo que <b>recompensa</b> e por quem <b>contrata, promove e desliga</b>.</p><p>Westrum observa a cultura pela forma como a informação circula. Na cultura generativa, quem traz más notícias é ouvido, as responsabilidades são compartilhadas, falhas geram investigação e não punição, e ideias novas são experimentadas. O DORA mede isso com um questionário baseado nessas características.</p><p><b>Erros comuns:</b> quadro de valores na parede sem mudança nos critérios de avaliação e promoção; tolerar uma pessoa tecnicamente brilhante com comportamento tóxico.</p>",
          k: ["Cultura é o pior comportamento que o líder tolera.",
              "Tipologia de Westrum: patológica (orientada a poder), burocrática (a regras) e generativa (a desempenho) — culturas generativas têm melhor desempenho de entrega (pesquisa DORA).",
              "Contratação, promoção e desligamento mostram os valores reais.",
              "Rituais: onboarding, celebrações, demos, post-mortems."] },
        { t: "Culture Hacking",
          c: "<p>Pequenas intervenções de baixo risco e alta visibilidade que mudam comportamentos e, aos poucos, a cultura — em vez de grandes programas de transformação. Ideia popularizada por Jurgen Appelo e pelo Culture Design Canvas (Gustavo Razzetti).</p><p><b>Exemplo:</b> para que problemas apareçam mais cedo, o líder passa a abrir a reunião semanal contando um erro próprio e o que aprendeu com ele. É barato, visível e reversível. Depois de um mês, observe se mais pessoas estão levantando riscos ou pedindo ajuda.</p><p>O canvas compara a cultura atual com a desejada e ajuda a escolher onde intervir. Ele funciona melhor preenchido junto com o time do que só pela liderança. Daniel Coyle aponta três habilidades de grupos com culturas fortes: <b>construir segurança</b>, <b>compartilhar vulnerabilidade</b> e <b>estabelecer propósito</b>. O exemplo acima trabalha a segunda.</p><p><b>Erros comuns:</b> \"hacks\" que são só endomarketing (pizza, brindes) e não mudam comportamento; lançar vários ao mesmo tempo e não saber qual funcionou.</p>",
          k: ["Exemplos: retrospectiva aberta à liderança, \"fail wall\" de aprendizados, demo day, prêmio para o melhor erro, rodízio de facilitação.",
              "Comece pequeno, meça o efeito, escale o que funciona.",
              "Culture Design Canvas: propósito, valores, prioridades, comportamentos, rituais, feedback, tomada de decisão, normas."] },
        { t: "Implantar cultura organizacional em IT Squads",
          c: "<p>Squads precisam de uma cultura local coerente com a da empresa. Use <b>team charters</b> e <b>working agreements</b> explícitos, construídos pelo próprio time.</p><p><b>Na prática:</b> um bom working agreement é concreto e verificável: \"PRs são revisados em até 1 dia útil\", \"deploy na sexta depois das 16h só em par\", \"das 9h às 12h, sem reuniões\". Frases vagas como \"respeito e colaboração\" não mudam comportamento.</p><p>No modelo descrito por Kniberg e Ivarsson no Spotify (2012), os <b>chapters</b> reúnem pessoas da mesma especialidade espalhadas por squads diferentes, com um líder de chapter, e as <b>guildas</b> são comunidades voluntárias de interesse que atravessam a empresa. O próprio texto se apresenta como retrato de um momento da empresa, não como modelo pronto para copiar.</p><p><b>Erros comuns:</b> acordos impostos pelo gestor; charter feito no kickoff e nunca revisado; cultura local em choque com a da empresa, o que gera atrito quando as pessoas mudam de time.</p>",
          k: ["Team canvas: propósito, objetivos, papéis, valores, regras, necessidades.",
              "Acordos técnicos: code review, padrões de qualidade, plantão, documentação.",
              "Chapters e guildas espalham práticas entre squads.",
              "Revise os acordos a cada trimestre ou quando o time mudar."] }
      ],
      pratica: "<p>Preencha um Culture Design Canvas para o seu time (atual × desejado). Escolha dois culture hacks para testar no próximo mês e defina como vai saber se funcionaram.</p>",
      perguntas: [
        ["Quais os três níveis de cultura de Schein?", "Artefatos, valores declarados e pressupostos básicos."],
        ["Quais as três culturas da tipologia de Westrum?", "Patológica, burocrática e generativa."],
        ["O que é um culture hack?", "Uma intervenção pequena, de baixo risco e visível, que muda um comportamento e ajuda a evoluir a cultura aos poucos."],
        ["Segundo Schein, por quais mecanismos o líder mais transmite cultura?", "Pelo que mede e controla, por como reage a crises, pelo que recompensa e por quem contrata, promove e desliga."],
        ["Como descobrir os pressupostos básicos reais de um time?", "Comparando o discurso com o que é de fato recompensado e tolerado: o que acontece com quem erra, quem é promovido, como as decisões são tomadas sob pressão."],
        ["Quais as três habilidades de culturas fortes segundo Daniel Coyle?", "Construir segurança, compartilhar vulnerabilidade e estabelecer propósito."],
        ["O que torna um working agreement eficaz?", "Ser construído pelo próprio time, concreto e verificável, e revisado periodicamente ou quando o time muda."],
        ["Situação: seu engenheiro mais produtivo humilha colegas em code reviews. O que você faz?", "Cultura é o pior comportamento que o líder tolera. Dê feedback direto e específico sobre o comportamento e o impacto, deixe clara a expectativa e acompanhe. Se não houver mudança, aplique consequências. Não agir custa a segurança psicológica e a retenção do resto do time."]
      ],
      aprofundamento: [
        ["Fearless Culture — Culture Design Canvas", "https://www.fearlessculture.design/canvas", "download gratuito do canvas (CC BY-ND). Comece por aqui."],
        ["Google re:Work — Understand team effectiveness", "https://rework.withgoogle.com/intl/en/guides/understand-team-effectiveness", "segurança psicológica e as dinâmicas de times eficazes."],
        ["GitLab Handbook — Values", "https://handbook.gitlab.com/handbook/values/", "exemplo real e público de valores traduzidos em comportamentos."],
        ["Netflix — Culture memo", "https://jobs.netflix.com/culture", "o documento de cultura mais conhecido do setor de tecnologia."],
        ["DORA — Generative organizational culture", "https://dora.dev/capabilities/generative-organizational-culture/", "como medir e melhorar a cultura segundo Westrum."]
      ],
      referencias: [
        ["Schein, E. <i>Organizational Culture and Leadership</i> (5ª ed., 2016)", ""],
        ["Westrum, R. \"A typology of organisational cultures\" — BMJ Quality & Safety (2004)", "https://qualitysafety.bmj.com/content/13/suppl_2/ii22"],
        ["DORA — Capabilities: Generative organizational culture", "https://dora.dev/capabilities/generative-organizational-culture/"],
        ["Razzetti, G. — Culture Design Canvas (Fearless Culture)", "https://www.fearlessculture.design/"],
        ["Appelo, J. <i>Managing for Happiness</i> (2016)", "https://management30.com/"],
        ["Coyle, D. <i>The Culture Code</i> (2018)", ""],
        ["Ivanov, A. — Team Canvas", "https://theteamcanvas.com/"],
        ["Kniberg, H.; Ivarsson, A. \"Scaling Agile @ Spotify with Tribes, Squads, Chapters & Guilds\" (2012)", "https://blog.crisp.se/wp-content/uploads/2012/11/SpotifyScaling.pdf"]
      ]
    },
    {
      titulo: "Gestão da Mudança em TI",
      resumo: "Como conduzir mudanças organizacionais e técnicas: dos modelos de mudança às práticas de registro de decisões e gestão do conhecimento.",
      topicos: [
        { t: "Gestão da Mudança",
          c: "<p>Modelos clássicos: <b>Kotter (8 passos)</b> — senso de urgência, coalizão, visão, comunicação, remover obstáculos, vitórias rápidas, consolidar, ancorar na cultura. <b>ADKAR</b> (Prosci), no nível individual: Awareness, Desire, Knowledge, Ability, Reinforcement. <b>Lewin</b>: descongelar, mudar, recongelar.</p><p><b>Exemplo (adotar trunk-based development):</b> <b>urgência</b>: mostrar que os merges de branches longas causaram dois incidentes e atrasam as entregas em uma semana. <b>Coalizão</b>: dois tech leads respeitados e a pessoa de QA. <b>Visão</b>: \"integrar ao tronco todo dia, com feature flags\". <b>Vitórias rápidas</b>: um time piloto mostra o lead time caindo pela metade em um mês. <b>Ancorar</b>: o novo fluxo entra no template de repositório e no onboarding.</p><p><b>ADKAR para diagnosticar:</b> avalie cada pessoa ou grupo nos cinco elementos, em ordem. O primeiro elemento com nota baixa é o <b>ponto de bloqueio</b>, e é nele que se age. Não adianta treinar (Knowledge) quem ainda não vê por que mudar (Desire).</p><p><b>Erros comuns:</b> anunciar a mudança por e-mail e considerar comunicada; declarar vitória cedo demais (Kotter alerta para isso); tratar toda resistência como má vontade, quando muitas vezes ela aponta um problema real do plano.</p>",
          k: ["Curva de Kübler-Ross adaptada: negação, resistência, exploração, comprometimento.",
              "Resistência costuma ser falta de informação, de habilidade ou de motivo — descubra qual.",
              "Mapa de stakeholders (poder × interesse).",
              "Em TI, gestão de mudanças do ITIL (change enablement) trata mudanças em serviços em produção."] },
        { t: "RFC e ADR",
          c: "<p><b>RFC</b> (Request for Comments): documento que propõe uma mudança técnica relevante e pede opinião antes da decisão — escala as discussões em organizações grandes. <b>ADR</b> (Architecture Decision Record, Michael Nygard): registro curto de uma decisão de arquitetura: <b>contexto</b>, <b>decisão</b>, <b>status</b> e <b>consequências</b>.</p><p><b>Estrutura típica de um RFC:</b> contexto e problema; proposta; <b>alternativas consideradas</b> e por que foram descartadas; riscos e impacto (segurança, custo, operação); plano de rollout e de rollback; perguntas em aberto; prazo para comentários e quem decide. O projeto Rust mantém todo o seu processo de RFCs em público, no GitHub, e é uma boa fonte de exemplos reais.</p><p><b>Quando usar cada um:</b> o RFC serve para decisões que afetam vários times e ainda estão em aberto, e busca opiniões <i>antes</i> de decidir. O ADR registra a decisão tomada. Um RFC aprovado costuma gerar um ou mais ADRs.</p><p><b>Erros comuns:</b> RFC para tudo, até decisões pequenas e reversíveis; RFC que vira votação ou poder de veto de qualquer pessoa; ADRs escritos meses depois, quando ninguém lembra mais o contexto.</p>",
          k: ["ADRs ficam no repositório, versionados com o código.",
              "ADRs não se editam; uma nova decisão substitui a anterior (status \"superseded\").",
              "RFC tem prazo de comentários e um responsável pela decisão.",
              "Ajudam no onboarding: \"por que fizemos assim?\"."] },
        { t: "Times adaptativos",
          c: "<p>Times que respondem bem a mudanças têm habilidades em forma de <b>T</b> (profundidade em uma área, amplitude em várias), baixa dependência de heróis e processos leves que evoluem.</p><p><b>Cynefin na prática:</b> em cada domínio, a ordem de ação muda. <b>Claro</b>: perceber, categorizar, responder, com boas práticas conhecidas (ex.: resetar a senha de um usuário). <b>Complicado</b>: perceber, analisar, responder, com especialistas (ex.: planejar a migração de um banco de dados). <b>Complexo</b>: sondar, perceber, responder, com experimentos seguros porque a relação de causa e efeito só aparece depois (ex.: lançar um produto novo, mudar a cultura). <b>Caótico</b>: agir, perceber, responder, estabilizando primeiro (ex.: incidente grave em produção).</p><p><b>Exemplo de bus factor:</b> só uma pessoa sabe operar o pipeline de faturamento. Se ela sair de férias, o fechamento do mês para. As ações são: pareamento nas próximas execuções, runbook escrito por quem ainda não sabe (sob orientação de quem sabe) e rodízio de quem executa.</p><p><b>Erros comuns:</b> tratar problemas complexos como complicados (contratar consultoria para \"o plano certo\" em vez de experimentar); celebrar heróis que resolvem tudo sozinhos, o que reforça a dependência.</p>",
          k: ["Pair/mob programming e rodízio de responsabilidades reduzem o bus factor.",
              "Cynefin (Dave Snowden): domínios claro, complicado, complexo e caótico pedem respostas diferentes.",
              "Resiliência: experimentos pequenos e reversíveis."] },
        { t: "Gestão Tática",
          c: "<p>O nível <b>tático</b> fica entre o estratégico (direção, longo prazo) e o operacional (execução do dia a dia): traduz a estratégia em planos de médio prazo, alocação de recursos e coordenação entre times.</p><p><b>Exemplo de planejamento trimestral</b> (proporções ilustrativas): um time de 6 pessoas em 12 semanas não tem 72 semanas-pessoa livres. Descontando férias, plantão e cerimônias, sobram talvez 55. A área combina, por exemplo, 60% para o roadmap, 20% para dívida técnica e 20% para demandas não planejadas, e revisa a proporção com os dados do trimestre anterior. As dependências entre times ficam num quadro visível, com dono e data.</p><p><b>Cadência:</b> revisão mensal de resultados (métricas, OKRs, riscos) e trimestral de prioridades. O objetivo é detectar desvios cedo e realocar pessoas ou escopo com base em dados, e não no fim do ano.</p><p><b>Erros comuns:</b> planejar 100% da capacidade e ter de sacrificar a qualidade no primeiro imprevisto; plano trimestral que ninguém consulta depois de aprovado; o nível tático repassando a estratégia sem traduzi-la em prioridades concretas.</p>",
          k: ["Planejamento trimestral, roadmap de área, gestão de dependências.",
              "Cadência de acompanhamento (business reviews mensais/trimestrais).",
              "Ferramentas: OKRs de área, portfólio kanban, capacity planning."] },
        { t: "Gestão do Conhecimento e do erro",
          c: "<p>Nonaka e Takeuchi mostram que conhecimento circula entre <b>tácito</b> (na cabeça das pessoas) e <b>explícito</b> (documentado) no modelo <b>SECI</b>: Socialização, Externalização, Combinação e Internalização. Gestão do erro: tratar falhas como oportunidade de aprendizado sistêmico.</p><p><b>SECI com exemplos:</b> <b>Socialização</b> (tácito → tácito): um dev júnior faz par com a sênior durante um incidente e aprende \"onde olhar\". <b>Externalização</b> (tácito → explícito): a sênior escreve o runbook. <b>Combinação</b> (explícito → explícito): vários runbooks viram um guia de operação do serviço. <b>Internalização</b> (explícito → tácito): o júnior pratica o guia num simulado até agir sem consultar.</p><p><b>Tipos de falha</b> (Edmondson, <i>Right Kind of Wrong</i>): as <b>básicas</b> têm causa única em território conhecido (esquecer um passo do checklist) e se previnem com processo; as <b>complexas</b> surgem da combinação de vários fatores (o incidente que só aconteceu porque três coisas deram errado juntas) e se reduzem com atenção aos sinais fracos; as <b>inteligentes</b> acontecem em território novo, depois de preparação, e na escala mínima necessária para aprender. Só as inteligentes devem ser buscadas.</p><p><b>Erros comuns:</b> post-mortem que termina em \"erro humano\" (o sistema permitiu o erro, e é isso que deve mudar); documentação que ninguém mantém; celebrar todo erro como aprendizado, inclusive os evitáveis.</p>",
          k: ["Post-mortems sem culpa: linha do tempo, fatores contribuintes, ações — foco no sistema, não em culpados.",
              "Documentação viva: wikis, runbooks, ADRs; o formato Diátaxis ajuda (tutoriais, guias, referência, explicação).",
              "Amy Edmondson classifica falhas em evitáveis, complexas e inteligentes (as que geram aprendizado em território novo)."] }
      ],
      pratica: "<p>Escreva um ADR real ou fictício sobre uma decisão técnica recente. Depois, planeje uma mudança (ex.: adotar trunk-based development) usando os 8 passos de Kotter e o ADKAR para as pessoas mais afetadas.</p>",
      perguntas: [
        ["Quais os elementos de um ADR?", "Título, contexto, decisão, status e consequências."],
        ["O que significa ADKAR?", "Awareness (consciência), Desire (desejo), Knowledge (conhecimento), Ability (habilidade) e Reinforcement (reforço)."],
        ["O que é o modelo SECI?", "O ciclo de conversão de conhecimento de Nonaka e Takeuchi: Socialização, Externalização, Combinação e Internalização."],
        ["Como usar o ADKAR para diagnosticar uma mudança travada?", "Avalie os cinco elementos em ordem e ache o primeiro com nota baixa, o ponto de bloqueio. Aja nele antes de avançar; por exemplo, não adianta treinar quem ainda não quer mudar."],
        ["Como agir em cada domínio do Cynefin?", "Claro: perceber, categorizar, responder. Complicado: perceber, analisar, responder. Complexo: sondar, perceber, responder. Caótico: agir, perceber, responder."],
        ["Qual a diferença de uso entre RFC e ADR?", "O RFC busca opiniões antes de uma decisão que ainda está em aberto; o ADR registra a decisão tomada e suas consequências."],
        ["Quais os três tipos de falha segundo Amy Edmondson?", "Básicas (causa única, território conhecido), complexas (combinação de fatores) e inteligentes (território novo, com preparação e na menor escala possível)."],
        ["Situação: o time resiste à nova ferramenta de observabilidade escolhida pela empresa. Como você conduz?", "Descubra o motivo com ADKAR: falta entender o porquê, falta querer ou falta saber usar? Envolva os mais resistentes como pilotos, mostre uma vitória concreta (um incidente resolvido mais rápido), ofereça treinamento e remova obstáculos (migração de dashboards). Ouça a resistência: ela pode revelar um problema real da escolha."]
      ],
      aprofundamento: [
        ["Enap — Gestão da Mudança", "https://suap.enap.gov.br/vitrine/curso/2057/", "curso gratuito em português; confira as datas de oferta na página."],
        ["Atlassian — Blameless postmortems", "https://www.atlassian.com/incident-management/postmortem/blameless", "como fazer post-mortems sem culpados."],
        ["Google SRE — Postmortem Culture", "https://sre.google/sre-book/postmortem-culture/", "capítulo gratuito sobre aprender com falhas."],
        ["ADR — templates e ferramentas", "https://adr.github.io/", "modelos de ADR prontos para usar."],
        ["Diátaxis", "https://diataxis.fr/", "framework gratuito para organizar documentação (gestão do conhecimento)."]
      ],
      referencias: [
        ["Kotter, J. <i>Liderando Mudanças</i> (1996) — 8 passos", "https://www.kotterinc.com/methodology/8-steps/"],
        ["Prosci — ADKAR Model", "https://www.prosci.com/methodology/adkar"],
        ["Lewin, K. — modelo de mudança em três etapas (1947)", ""],
        ["Nygard, M. \"Documenting Architecture Decisions\" (2011)", "https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions"],
        ["ADR GitHub organization — templates e ferramentas", "https://adr.github.io/"],
        ["Snowden, D.; Boone, M. \"A Leader's Framework for Decision Making\" — HBR (2007) — Cynefin", "https://hbr.org/2007/11/a-leaders-framework-for-decision-making"],
        ["Nonaka, I.; Takeuchi, H. <i>Criação de Conhecimento na Empresa</i> (1995)", ""],
        ["Edmondson, A. <i>Right Kind of Wrong</i> (2023)", ""],
        ["Google SRE — Postmortem Culture", "https://sre.google/sre-book/postmortem-culture/"],
        ["Diátaxis — framework de documentação", "https://diataxis.fr/"],
        ["Rust — processo público de RFCs (GitHub)", "https://github.com/rust-lang/rfcs"]
      ]
    },
    {
      titulo: "Advanced Leadership Skills",
      resumo: "O que sustenta um líder no longo prazo: motivar sem depender de recompensa externa, liderar com presença, aprender continuamente e liderar com responsabilidade social.",
      topicos: [
        { t: "Motivação 4.0",
          c: "<p>Daniel Pink (<i>Motivação 3.0 / Drive</i>) mostra que, para trabalho criativo e cognitivo, recompensas do tipo \"se fizer isso, ganha aquilo\" funcionam mal. O que motiva é: <b>Autonomia</b>, <b>Maestria</b> (domínio) e <b>Propósito</b>. \"Motivação 4.0\" é a leitura atual disso na era digital, somando bem-estar, flexibilidade e significado.</p><p><b>Atenção ao termo:</b> \"Motivação 4.0\" não é um conceito acadêmico consolidado. A base teórica continua sendo Pink e a Teoria da Autodeterminação.</p><p><b>Na prática:</b> Pink cita o \"problema da vela\" (Glucksberg): o grupo que recebeu prêmio em dinheiro levou mais tempo para resolver, porque a recompensa estreita o foco. Ele descreve a autonomia sobre quatro coisas: <b>tarefa</b>, <b>tempo</b>, <b>técnica</b> e <b>time</b>. Em tecnologia, isso vira deixar o time decidir <i>como</i> resolver o problema, oferecer uma trilha técnica que permita crescer sem virar gestor (maestria) e ligar cada entrega ao impacto no cliente (propósito).</p><p>Herzberg ajuda a ordenar o trabalho: primeiro resolva os fatores higiênicos (salário abaixo do mercado, ferramentas ruins, plantão abusivo), porque, enquanto eles incomodam, falar de propósito soa vazio.</p><p><b>Erros comuns:</b> bônus individual por entregas em trabalho que depende do time; microgerenciamento, que tira a autonomia; propósito que existe só no discurso.</p>",
          k: ["Salário justo tira dinheiro da mesa; acima disso, motivação é intrínseca.",
              "Teoria da Autodeterminação (Deci & Ryan): autonomia, competência e pertencimento.",
              "Teoria dos dois fatores de Herzberg: higiênicos (evitam insatisfação) × motivacionais."] },
        { t: "Mindful Leadership",
          c: "<p>Liderança com atenção plena: estar presente, observar sem julgar e responder em vez de reagir. Programas como o <b>Search Inside Yourself</b> (criado no Google) unem mindfulness e inteligência emocional.</p><p><b>Na prática:</b> o Search Inside Yourself, criado por Chade-Meng Tan no Google, organiza o treino em três partes: <b>treino da atenção</b>, <b>autoconhecimento e autocontrole</b> e <b>hábitos mentais úteis</b> (como empatia e compaixão). Para um líder, isso aparece em momentos concretos: perceber a própria irritação antes de responder a um incidente, escutar um 1:1 sem olhar o celular, esperar antes de responder uma mensagem tensa.</p><p>A OMS define o burnout na CID-11 como resultado do <b>estresse crônico no trabalho que não foi gerenciado com sucesso</b>, com três dimensões: exaustão, distanciamento mental ou cinismo em relação ao trabalho e redução da eficácia profissional.</p><p><b>Erros comuns:</b> oferecer meditação como resposta a uma sobrecarga que é estrutural (a própria definição da OMS aponta para o ambiente de trabalho); o líder que prega equilíbrio e manda mensagens à meia-noite.</p>",
          k: ["Práticas simples: respiração antes de reuniões difíceis, check-ins no início de encontros, uma tarefa por vez.",
              "Reduz estresse e melhora a qualidade das decisões.",
              "Prevenção de burnout (reconhecido pela OMS como fenômeno ocupacional na CID-11)."] },
        { t: "Lifelong Learning",
          c: "<p>Em tecnologia, o conhecimento envelhece rápido. Aprender continuamente é parte do trabalho do líder — e ele serve de modelo para o time.</p><p><b>O que a pesquisa mostra:</b> <i>Make It Stick</i> reúne as técnicas com mais evidência: <b>prática de recuperação</b> (testar-se em vez de reler), <b>espaçamento</b> (revisar em intervalos crescentes) e <b>intercalação</b> (misturar tipos de problema). Reler e grifar dão uma <i>ilusão de fluência</i>: o texto parece familiar, mas pouco fica na memória. O curso <i>Learning How to Learn</i> (Barbara Oakley) acrescenta a alternância entre o modo <b>focado</b> e o <b>difuso</b> do pensamento.</p><p><b>Na prática:</b> as perguntas de revisão deste guia são prática de recuperação. Responda antes de abrir a resposta e volte a elas dias depois. O modelo 70-20-10 (Lombardo e Eichinger) sugere que a maior parte do desenvolvimento vem de desafios no trabalho (70%), depois de relações como mentoria e feedback (20%) e só uma parte menor de cursos (10%).</p><p><b>Erros comuns:</b> acumular cursos sem aplicar nada; estudar só o que já domina; não reservar tempo na agenda para aprender.</p>",
          k: ["Técnica Feynman: explique de forma simples para testar se entendeu.",
              "Repetição espaçada e prática de recuperação (flashcards) — base científica sólida para memorização.",
              "Aprenda em público: escreva, apresente, ensine.",
              "Rede de pares (outros líderes) para trocar experiências."] },
        { t: "ESG, Diversidade e inclusão",
          c: "<p><b>ESG</b> (Environmental, Social, Governance) avalia empresas por impacto ambiental, social e qualidade de governança. Em TI: <b>green software</b> e eficiência energética (E), diversidade, inclusão e acessibilidade (S), ética, transparência e compliance (G).</p><p><b>Na prática (E):</b> a especificação SCI, publicada como norma <b>ISO/IEC 21031:2024</b>, calcula uma taxa, e não um total: SCI = ((E × I) + M) por R. E é a energia consumida, I a intensidade de carbono da eletricidade, M as emissões embutidas no hardware e R a unidade funcional (por usuário, por transação, por chamada de API). Assim, dá para comparar versões do mesmo sistema e ver se uma otimização reduziu o carbono por uso.</p><p><b>Na prática (S):</b> no Brasil, a Lei Brasileira de Inclusão (Lei 13.146/2015, art. 63) obriga sites de empresas com sede ou representação no país a serem acessíveis, e a WCAG é a referência técnica. A Lei 14.611/2023 exige que empresas com 100 ou mais empregados publiquem relatórios semestrais de transparência salarial.</p><p><b>Erros comuns:</b> greenwashing (divulgar metas sem medir); tratar diversidade só na contratação e ignorar inclusão, promoção e retenção; deixar acessibilidade para \"depois do MVP\".</p>",
          k: ["Green Software Foundation: medir e reduzir a intensidade de carbono do software (SCI).",
              "Pilar de Sustentabilidade do Well-Architected.",
              "Inclusão: equidade salarial, processos seletivos estruturados, acessibilidade digital, grupos de afinidade.",
              "Lei 14.611/2023: igualdade salarial entre mulheres e homens no Brasil (relatórios de transparência)."] }
      ],
      pratica: "<p>Monte seu plano pessoal de desenvolvimento para os próximos 6 meses: 2 competências técnicas, 2 de liderança, como vai praticar e como vai medir. Proponha também uma ação de ESG possível no seu time (ex.: medir a pegada de carbono de um serviço ou revisar a acessibilidade de uma tela).</p>",
      perguntas: [
        ["Quais os três elementos da motivação intrínseca segundo Daniel Pink?", "Autonomia, maestria e propósito."],
        ["O que significa ESG?", "Environmental, Social and Governance — critérios ambientais, sociais e de governança."],
        ["O que diz a teoria dos dois fatores de Herzberg?", "Fatores higiênicos (salário, condições) evitam insatisfação, mas não motivam; fatores motivacionais (reconhecimento, crescimento, o trabalho em si) geram satisfação."],
        ["Por que recompensas do tipo \"se fizer, ganha\" atrapalham trabalho criativo?", "Porque estreitam o foco na recompensa e prejudicam a busca por soluções não óbvias, como no problema da vela citado por Pink. Funcionam melhor para tarefas simples e mecânicas."],
        ["Quais as três dimensões do burnout segundo a OMS (CID-11)?", "Exaustão, distanciamento mental ou cinismo em relação ao trabalho e redução da eficácia profissional."],
        ["Quais técnicas de estudo têm mais evidência segundo <i>Make It Stick</i>?", "Prática de recuperação, espaçamento e intercalação. Reler e grifar rendem pouco."],
        ["Como se calcula o SCI (Software Carbon Intensity)?", "SCI = ((E × I) + M) por R: energia × intensidade de carbono, mais emissões embutidas do hardware, dividido por uma unidade funcional."],
        ["Situação: depois de uma reorganização o time está desmotivado, e o RH sugere um bônus. O que você faz?", "Primeiro, escute em 1:1s o que mudou. Confira os fatores higiênicos (Herzberg); o bônus pode ajudar se o problema for dinheiro, mas não resolve perda de autonomia, de propósito ou de pertencimento. Devolva decisões ao time, explique o porquê da reorganização e ligue o novo escopo ao impacto no cliente."]
      ],
      aprofundamento: [
        ["Dan Pink — The puzzle of motivation (TED)", "https://www.ted.com/talks/dan_pink_the_puzzle_of_motivation", "palestra de 18 min sobre autonomia, maestria e propósito. Comece por aqui."],
        ["Coursera — Learning How to Learn", "https://www.coursera.org/learn/learning-how-to-learn", "curso gratuito sobre técnicas de aprendizado com base científica."],
        ["Green Software Foundation — Green Software Practitioner", "https://learn.greensoftware.foundation/", "curso gratuito de software sustentável (o “E” do ESG em TI)."],
        ["W3C — Digital Accessibility Foundations", "https://www.w3.org/WAI/courses/foundations-course/", "curso gratuito de acessibilidade digital (inclusão)."],
        ["Escola Virtual.Gov — Gestão Pessoal: Base da Liderança", "https://www.escolavirtual.gov.br/curso/163", "curso gratuito em português sobre autogestão."]
      ],
      referencias: [
        ["Pink, D. <i>Motivação 3.0</i> (Drive, 2009)", "https://www.danpink.com/books/drive/"],
        ["Deci, E.; Ryan, R. — Self-Determination Theory", "https://selfdeterminationtheory.org/"],
        ["Herzberg, F. \"One More Time: How Do You Motivate Employees?\" — HBR (1968)", "https://hbr.org/2003/01/one-more-time-how-do-you-motivate-employees"],
        ["Tan, C.-M. <i>Search Inside Yourself</i> (2012) — SIYLI", "https://siyli.org/"],
        ["OMS — Burn-out an \"occupational phenomenon\" (CID-11)", "https://www.who.int/news/item/28-05-2019-burn-out-an-occupational-phenomenon-international-classification-of-diseases"],
        ["Brown, P.; Roediger, H.; McDaniel, M. <i>Make It Stick</i> (2014) — ciência do aprendizado", ""],
        ["Green Software Foundation — Software Carbon Intensity (SCI)", "https://greensoftware.foundation/"],
        ["Lei 14.611/2023 — Igualdade salarial (Planalto)", "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14611.htm"],
        ["UN Global Compact / PRI — origem do termo ESG (\"Who Cares Wins\", 2004)", "https://www.unglobalcompact.org/"],
        ["Oakley, B. <i>A Mind for Numbers</i> (2014) e o curso <i>Learning How to Learn</i>", "https://www.coursera.org/learn/learning-how-to-learn"],
        ["Lombardo, M.; Eichinger, R. <i>The Career Architect Development Planner</i> (1996) — modelo 70-20-10", ""],
        ["ISO/IEC 21031:2024 — Software Carbon Intensity (SCI) specification", "https://www.iso.org/standard/86612.html"],
        ["Lei 13.146/2015 — Lei Brasileira de Inclusão (Planalto)", "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13146.htm"]
      ]
    }
  ],
  challenge: {
    intro: "Sugestão de projeto final: consolide tudo num plano de operação e liderança do produto (mais o hackathon e a atividade individual presencial previstos no curso).",
    entregas: ["Estratégia de cloud, estimativa de custos e práticas de FinOps.", "SLOs, alertas e stack de observabilidade.", "OKRs do trimestre e rituais de gestão de pessoas (1:1, feedback, PDI).", "Plano de cultura e de gestão da mudança (Kotter/ADKAR) com ADRs.", "Apresentação final (pitch) para um board fictício."]
  }
});
