window.CURSO.push({
  n: 2,
  periodo: "Meses 3 e 4",
  titulo: "Times, Gestão Ágil e Finanças",
  descricao: "Como montar e estruturar times de alta performance, geri-los no dia a dia ágil, cuidar do dinheiro (orçamento e sourcing) e se comunicar e negociar bem.",
  disciplinas: [
    {
      titulo: "Montando Equipes de Alta Performance",
      resumo: "Estruturas organizacionais e modelos de escala ágil para montar times que entregam valor com autonomia e alinhamento.",
      topicos: [
        { t: "Gestão 4.0",
          c: "<p>Gestão adaptada à era digital: organização em rede, decisões guiadas por dados, autonomia com alinhamento, aprendizado contínuo. Contrasta com a gestão de comando e controle da era industrial.</p><p><b>Na prática:</b> Appelo organiza o Management 3.0 em seis visões: energizar as pessoas, empoderar os times, alinhar restrições, desenvolver competências, fazer a estrutura crescer e melhorar tudo. O Beyond Budgeting propõe separar três coisas que o orçamento anual mistura: <b>metas</b> (aonde queremos chegar), <b>previsões</b> (aonde achamos que vamos chegar) e <b>alocação de recursos</b>, que passa a ser dinâmica em vez de anual (Bogsnes).</p><p><b>Exemplo:</b> em vez de o gestor aprovar cada ferramenta que o time adota, a empresa define restrições (orçamento, segurança, LGPD) e o time decide dentro delas.</p><p><b>Erros comuns:</b> \"horizontalizar\" sem deixar claro quem decide o quê, o que faz surgir uma hierarquia informal e invisível; dar autonomia sem dar informação (metas, números, contexto).</p>",
          k: ["Hierarquias mais planas e times multidisciplinares.",
              "Decisão descentralizada, perto de quem tem a informação.",
              "Uso intensivo de dados e automação.",
              "Referências: Management 3.0 (Jurgen Appelo), Beyond Budgeting."] },
        { t: "Estrutura organizacional",
          c: "<p>Estruturas clássicas: <b>funcional</b> (por especialidade), <b>divisional</b> (por produto/região), <b>matricial</b> (dupla subordinação) e <b>em rede/times</b>. A <b>Lei de Conway</b> diz que sistemas refletem a estrutura de comunicação da organização que os cria.</p><p><b>Exemplo (e-commerce com Team Topologies):</b> times <b>stream-aligned</b> para \"busca e descoberta\", \"checkout\" e \"pós-venda\"; um time de <b>plataforma</b> que oferece deploy, observabilidade e bancos como serviço (modo X-as-a-Service); um time <b>enabling</b> de performance que passa algumas semanas com cada time ensinando práticas (facilitating); um time de <b>subsistema complicado</b> para o motor de antifraude, que exige especialistas.</p><p>O modo <b>collaboration</b> deve ser temporário, por exemplo quando dois times descobrem juntos uma nova API. Se virar permanente, é sinal de que a fronteira entre eles está errada. A carga cognitiva é o limite: um time não deve cuidar de mais domínios do que consegue entender a fundo.</p><p><b>Erros comuns:</b> time de plataforma que vira fila de tickets, em vez de oferecer autoatendimento; reorganizar a cada trimestre; estrutura matricial sem regra clara de quem decide prioridades.</p>",
          k: ["<b>Team Topologies</b> (Skelton & Pais): stream-aligned, platform, enabling e complicated-subsystem.",
              "Três modos de interação: collaboration, X-as-a-Service e facilitating.",
              "Manobra inversa de Conway: desenhe os times pensando na arquitetura que você quer.",
              "Carga cognitiva do time como critério de desenho."] },
        { t: "Modelos de criação de Squads",
          c: "<p>Squad = time pequeno (5 a 9 pessoas), multidisciplinar, dono de uma missão ou parte do produto, com autonomia para decidir como entregar.</p><p><b>Exemplo:</b> squad \"Onboarding de clientes PJ\", com a missão de aumentar a ativação de contas PJ no primeiro mês e uma métrica clara (% de contas que fazem a primeira transação em 30 dias). Composição típica: uma pessoa de produto, uma de design, quatro a seis de engenharia (incluindo qualidade) e acesso a dados. Ele é dono do front, da API e dos dados dessa jornada, e consegue entregar sem pedir nada a outros times na maior parte das vezes.</p><p>Team Topologies defende times <b>estáveis e de longa duração</b>: um time leva tempo para ganhar confiança e conhecimento do domínio, e trocar pessoas a cada projeto zera esse ganho. Leve o trabalho ao time, e não o contrário.</p><p><b>Erros comuns:</b> só trocar o nome do antigo time para \"squad\"; squad sem pessoa de produto de verdade; squad que depende de três outros times para qualquer entrega.</p>",
          k: ["Cortar por jornada do cliente, domínio de negócio, produto ou plataforma.",
              "Evite squads por camada técnica (front, back) — geram dependências.",
              "Regra das duas pizzas (Amazon).",
              "Estabilidade do time > realocação constante de pessoas."] },
        { t: "Unfix, Spotify Model, LeSS, SAFe",
          c: "<p>Modelos para escalar agilidade:</p><p><b>Como escolher:</b> a primeira pergunta é se você precisa escalar. O LeSS recomenda antes <b>\"desescalar\"</b>: reduzir dependências e o número de papéis. O LeSS básico é pensado para 2 a 8 times num mesmo produto (acima disso, há o LeSS Huge). O SAFe organiza os times em Agile Release Trains, que planejam juntos num PI Planning de cerca de dois dias a cada Program Increment de 8 a 12 semanas.</p><p>Sobre o Spotify: Jeremiah Lee, que foi gerente de produto lá, escreveu em 2020 que o modelo foi só uma aspiração, nunca implementada por completo na empresa, e na prática virou uma matriz mal resolvida, com gestores de engenharia sem responsabilidade pela entrega. Os próprios autores do texto de 2012 desaconselham copiá-lo.</p><p><b>Erros comuns:</b> adotar um framework para \"ser ágil\" sem mudar orçamento, metas e fluxo de decisão; copiar nomes (tribo, guilda) sem os princípios; escolher o framework antes de entender as dependências entre os times.</p>",
          k: ["<b>Spotify Model:</b> Squads, Tribes, Chapters (mesma especialidade entre squads) e Guilds (comunidades de interesse). O próprio Spotify diz que não era um framework e nunca foi implementado de forma pura — copie princípios, não a estrutura.",
              "<b>LeSS (Large-Scale Scrum):</b> um Product Owner e um backlog para vários times; minimalista, pede mudança organizacional profunda.",
              "<b>SAFe:</b> framework prescritivo com Agile Release Trains, PI Planning trimestral, portfólio lean. Popular em grandes corporações; criticado por ser pesado.",
              "<b>unFIX (Jurgen Appelo):</b> blocos combináveis (Base, Crew, Forum, Turf) para desenhar a organização sob medida e permitir reorganizações frequentes."] },
        { t: "Otimizando equipes",
          c: "<p>Alta performance vem de <b>segurança psicológica</b> — a descoberta principal do Projeto Aristóteles do Google — seguida de confiabilidade, estrutura e clareza, significado e impacto.</p><p><b>Na prática:</b> o papel do líder muda conforme o estágio de Tuckman. No <b>forming</b>, dê clareza de objetivo e papéis. No <b>storming</b>, traga os conflitos para a mesa e combine acordos, sem abafá-los. No <b>norming</b>, reforce os acordos e passe decisões para o time. No <b>performing</b>, remova obstáculos e proteja o time. Entradas e saídas de pessoas podem levar o time de volta a estágios anteriores.</p><p>Lencioni organiza as cinco disfunções em pirâmide: sem <b>confiança</b>, o time foge do <b>conflito</b> produtivo (vive numa \"harmonia artificial\"); sem conflito, não há <b>comprometimento</b> real com as decisões; sem comprometimento, ninguém cobra ninguém (<b>responsabilização</b>); e, sem cobrança, cada um cuida da própria área em vez do <b>resultado</b> do time.</p><p><b>Erros comuns:</b> desmontar um time que chegou ao performing para \"espalhar talentos\"; confundir ausência de conflito com time saudável.</p>",
          k: ["Modelo de Tuckman: forming, storming, norming, performing (e adjourning).",
              "5 Disfunções de um Time (Lencioni): falta de confiança, medo de conflito, falta de comprometimento, evitar responsabilização, desatenção aos resultados.",
              "Reduza WIP e dependências entre times.",
              "Métricas DORA como termômetro de entrega."] },
        { t: "Performance em times híbridos, remotos e on-site",
          c: "<p>Cada modelo pede práticas diferentes. No remoto, o padrão deve ser <b>comunicação assíncrona e escrita</b>; no híbrido, o maior risco é criar duas classes de pessoas (quem está no escritório e quem não está).</p><p><b>Exemplo de acordo de time remoto:</b> sobreposição obrigatória das 10h às 14h; mensagens no chat respondidas em até 4 horas úteis; urgência só por telefone ou pager; decisões registradas num documento, nunca só em call; reunião sem pauta escrita pode ser recusada.</p><p>O handbook do GitLab, empresa totalmente remota, defende o <b>handbook first</b>: a resposta deve estar escrita num lugar que todos acessam, e a reunião serve para discutir o documento, não para substituí-lo.</p><p><b>Erros comuns:</b> medir presença pelo status \"online\" no chat; decisões tomadas no corredor ou no café com quem está no escritório; replicar no remoto a agenda cheia de reuniões do presencial.</p>",
          k: ["Documente decisões (ADRs, RFCs, wikis).",
              "Acordos de time: horários de sobreposição, tempo de resposta, canais.",
              "Encontros presenciais com propósito (planejamento, integração).",
              "Se uma pessoa está remota, todos entram na reunião pelo próprio notebook.",
              "Meça resultado, não presença."] },
        { t: "Diversidade nas equipes",
          c: "<p>Times diversos (gênero, raça, idade, origem, neurodiversidade, formação) tomam decisões melhores e criam produtos que servem mais gente — mas só se houver <b>inclusão</b>: diversidade é convidar para a festa, inclusão é chamar para dançar (frase atribuída a Vernā Myers).</p><p><b>Na prática:</b> entrevistas <b>estruturadas</b> (mesmas perguntas, critérios definidos antes e notas dadas separadamente por cada entrevistador) preveem melhor o desempenho do que conversas livres, segundo a meta-análise de Schmidt e Hunter (1998), e reduzem o espaço para o \"gostei dele\". O mesmo vale para promoções: critérios escritos por nível (career ladder) e calibração entre gestores.</p><p>Inclusão também é ajuste do ambiente: pauta enviada antes da reunião ajuda quem processa melhor por escrito; rodadas de fala evitam que as mesmas vozes dominem; adaptações para pessoas neurodivergentes (menos ruído, instruções escritas) costumam beneficiar todo o time.</p><p><b>Erros comuns:</b> olhar só para a contratação e ignorar retenção e promoção; contratar uma pessoa de um grupo sub-representado e esperar que ela \"represente\" o grupo; não medir representatividade por nível hierárquico.</p>",
          k: ["Processos seletivos estruturados reduzem viés.",
              "Vagas com linguagem inclusiva; painéis de entrevista diversos.",
              "Atenção a viés inconsciente em promoções e avaliações.",
              "Métricas de representatividade por nível, não só no total."] }
      ],
      pratica: "<p>Desenhe a topologia de times de uma empresa fictícia de e-commerce com 60 engenheiros usando Team Topologies: defina os times stream-aligned, as plataformas, um enabling team e os modos de interação entre eles.</p>",
      perguntas: [
        ["O que diz a Lei de Conway?", "Organizações produzem sistemas que copiam suas estruturas de comunicação."],
        ["Quais os quatro tipos de time em Team Topologies?", "Stream-aligned, Platform, Enabling e Complicated-subsystem."],
        ["Qual o fator mais importante de times eficazes no Projeto Aristóteles?", "Segurança psicológica."],
        ["Quais os três modos de interação em Team Topologies, e qual deve ser temporário?", "Collaboration, X-as-a-Service e facilitating. A colaboração deve ser temporária; se for permanente, a fronteira entre os times provavelmente está errada."],
        ["O que é a manobra inversa de Conway?", "Desenhar a estrutura dos times de acordo com a arquitetura desejada, já que o sistema tende a copiar a comunicação da organização."],
        ["Qual a principal diferença de abordagem entre LeSS e SAFe?", "O LeSS é minimalista (um backlog, um PO para vários times) e pede desescalar antes de escalar; o SAFe é prescritivo, com mais papéis, trens e eventos como o PI Planning."],
        ["Qual a base da pirâmide de Lencioni e por quê?", "A falta de confiança. Sem ela, o time evita conflitos, e isso compromete todas as camadas acima: comprometimento, responsabilização e foco em resultados."],
        ["Situação: seu squad depende de três outros times para qualquer entrega e vive bloqueado. O que você faz?", "Mapeie as dependências e seus motivos. Redesenhe as fronteiras por fluxo de valor, traga para o squad as capacidades que ele usa sempre e transforme o que é comum em plataforma oferecida como serviço. Confira se a carga cognitiva de cada time continua razoável."]
      ],
      aprofundamento: [
        ["Google re:Work — Understand team effectiveness (Projeto Aristóteles)", "https://rework.withgoogle.com/intl/en/guides/understand-team-effectiveness", "a pesquisa das 5 dinâmicas de times eficazes + guia de discussão para o time. Comece por aqui."],
        ["Atlassian Team Playbook", "https://www.atlassian.com/team-playbook", "workshops gratuitos (plays) para alinhamento, papéis, saúde do time e retrospectivas."],
        ["Kniberg & Ivarsson — Scaling Agile @ Spotify (PDF)", "https://blog.crisp.se/wp-content/uploads/2012/11/SpotifyScaling.pdf", "o artigo original de squads, tribes, chapters e guilds."],
        ["Team Topologies — Key Concepts", "https://teamtopologies.com/key-concepts", "resumo gratuito dos 4 tipos de time e 3 modos de interação."],
        ["GitLab — guia de trabalho remoto (all-remote)", "https://handbook.gitlab.com/handbook/company/culture/all-remote/", "o manual público de uma empresa 100% remota."],
        ["unFIX — site oficial", "https://unfix.com/", "os padrões de estrutura organizacional do Jurgen Appelo, com ilustrações."]
      ],
      referencias: [
        ["Skelton, M.; Pais, M. <i>Team Topologies</i> (2019)", "https://teamtopologies.com/key-concepts"],
        ["Conway, M. \"How Do Committees Invent?\" (1968) — Lei de Conway", "https://www.melconway.com/Home/Committees_Paper.html"],
        ["Kniberg, H.; Ivarsson, A. \"Scaling Agile @ Spotify\" (2012)", "https://blog.crisp.se/wp-content/uploads/2012/11/SpotifyScaling.pdf"],
        ["LeSS — Large-Scale Scrum (site oficial)", "https://less.works/"],
        ["SAFe — Scaled Agile Framework (site oficial)", "https://scaledagileframework.com/"],
        ["unFIX — Jurgen Appelo (site oficial)", "https://unfix.com/"],
        ["Appelo, J. <i>Management 3.0</i> (2010)", "https://management30.com/"],
        ["Google re:Work — Projeto Aristóteles (times eficazes)", "https://rework.withgoogle.com/"],
        ["Edmondson, A. <i>The Fearless Organization</i> (2018)", ""],
        ["Tuckman, B. \"Developmental Sequence in Small Groups\" (1965)", ""],
        ["Lencioni, P. <i>Os 5 Desafios das Equipes</i> (2002)", ""],
        ["GitLab — The Remote Playbook / handbook de trabalho remoto", "https://handbook.gitlab.com/handbook/company/culture/all-remote/"],
        ["Bogsnes, B. <i>Implementing Beyond Budgeting</i> (2ª ed., 2016)", ""],
        ["Lee, J. \"Spotify's Failed #SquadGoals\" (2020)", "https://www.jeremiahlee.com/posts/failed-squad-goals/"],
        ["Schmidt, F.; Hunter, J. \"The Validity and Utility of Selection Methods in Personnel Psychology\" — Psychological Bulletin (1998)", ""]
      ]
    },
    {
      titulo: "Gestão de Times Ágeis e Multidisciplinares",
      resumo: "O dia a dia da gestão ágil: do refinamento ao planejamento, backlog, retrospectivas e as métricas que mostram a saúde do time.",
      topicos: [
        { t: "Gestão de equipes ágeis",
          c: "<p>Manifesto Ágil (2001): <b>indivíduos e interações</b>, <b>software funcionando</b>, <b>colaboração com o cliente</b> e <b>responder a mudanças</b>. Frameworks: <b>Scrum</b> (sprints, papéis e cerimônias definidos) e <b>Kanban</b> (fluxo contínuo, limite de WIP).</p><p><b>Na prática:</b> o Scrum Guide 2020 fala de um único Scrum Team, sem sub-times nem hierarquia, comprometido com um Sprint Goal por sprint e com um Product Goal de longo prazo. O Kanban parte do processo atual: não impõe papéis nem cerimônias, e o sistema evolui aos poucos a partir do quadro, dos limites de WIP e das políticas explícitas.</p><p><b>Erros comuns:</b> transformar a Daily em reunião de status para o gestor (no Scrum Guide ela é dos Developers, dura 15 minutos e serve para inspecionar o progresso em direção ao Sprint Goal); adotar os rituais sem mudar quem decide (\"ágil de fachada\"); ignorar o limite de WIP porque \"tudo é prioridade\".</p>",
          k: ["Scrum: Product Owner, Scrum Master, Developers; eventos: Sprint, Planning, Daily, Review, Retro.",
              "Kanban: visualizar o fluxo, limitar WIP, gerenciar o fluxo, políticas explícitas, loops de feedback, melhoria contínua.",
              "O gestor ágil protege o time, remove impedimentos e cuida do sistema de trabalho."] },
        { t: "Do Design ao Planning",
          c: "<p>O caminho da ideia até o trabalho planejado: discovery → épico → histórias → refinamento → planning.</p><p><b>Exemplo:</b> épico \"pagar com Pix no app\". No story map, a primeira release pode ter só \"gerar QR Code no pagamento\" e \"confirmar o pagamento recebido\", e ficam para depois o Pix Copia e Cola, o agendamento e o estorno. Cada fatia é <b>vertical</b>: atravessa tela, API e banco e entrega algo que o usuário usa de ponta a ponta, em vez de \"primeiro todo o back-end, depois o front\".</p><p>Critério de aceite em Gherkin: <i>Dado</i> um pedido de R$ 50 aguardando pagamento, <i>quando</i> o cliente escolhe Pix, <i>então</i> o app mostra um QR Code válido por 30 minutos.</p><p><b>Erros comuns:</b> histórias técnicas disfarçadas (\"como desenvolvedor, quero criar a tabela…\"); histórias grandes demais para caber em uma sprint; planning que vira só uma rodada de estimativas, sem Sprint Goal.</p>",
          k: ["User Story: \"Como [persona], quero [ação] para [benefício]\".",
              "INVEST: Independente, Negociável, Valiosa, Estimável, Pequena (Small), Testável.",
              "Critérios de aceite em formato Gherkin (Dado/Quando/Então).",
              "Story mapping (Jeff Patton) para fatiar releases.",
              "Definition of Ready e Definition of Done."] },
        { t: "Backlog e retrospectiva",
          c: "<p>O backlog deve ser <b>DEEP</b>: Detalhado de forma adequada, Estimado, Emergente e Priorizado. A retrospectiva é o motor de melhoria contínua do time.</p><p><b>Exemplos de cálculo:</b> RICE = (Alcance × Impacto × Confiança) ÷ Esforço. No WSJF, o Cost of Delay soma valor para o usuário/negócio, criticidade no tempo e redução de risco/habilitação de oportunidade, e o total é dividido pelo tamanho do trabalho. Um item com CoD 20 e tamanho 5 (WSJF 4) passa na frente de outro com CoD 30 e tamanho 15 (WSJF 2): fazer antes o que é pequeno e valioso reduz o custo total do atraso (Reinertsen).</p><p><b>Retro:</b> no Scrum Guide, a Retrospective inspeciona pessoas, interações, processos, ferramentas e a Definition of Done. Varie o formato para evitar respostas no piloto automático e abra com a \"Prime Directive\" de Norm Kerth: todos fizeram o melhor trabalho possível com o que sabiam naquele momento.</p><p><b>Erros comuns:</b> backlog com centenas de itens que nunca serão feitos; priorização por quem fala mais alto (HiPPO — a opinião de quem ganha mais); retro sem ações ou com ações sem dono.</p>",
          k: ["Priorização: MoSCoW, RICE (Reach, Impact, Confidence, Effort), WSJF (Cost of Delay / duração), Kano.",
              "Formatos de retro: Start/Stop/Continue, 4Ls, Sailboat, Mad/Sad/Glad, linha do tempo.",
              "Saia de toda retro com 1 a 3 ações com dono e prazo.",
              "Revise na retro seguinte se as ações foram feitas."] },
        { t: "Gestão de indicadores",
          c: "<p>Meça o <b>fluxo</b> e os <b>resultados</b>, não a ocupação das pessoas. Cuidado com a <b>Lei de Goodhart</b>: quando uma medida vira meta, deixa de ser uma boa medida.</p><p><b>Na prática:</b> a <b>Lei de Little</b> liga as métricas de fluxo: tempo médio no sistema = WIP médio ÷ throughput médio. Um time com 20 itens em andamento que termina 10 por semana leva cerca de 2 semanas por item; com o WIP em 10, esse tempo cai para cerca de 1 semana sem ninguém trabalhar mais rápido. Para previsões, prefira percentis (\"85% dos itens terminam em até 8 dias\") a médias (Vacanti).</p><p>O SPACE recomenda combinar métricas de pelo menos três dimensões, misturando dados de sistema com a percepção das pessoas (pesquisas), porque nenhuma métrica sozinha mede produtividade.</p><p><b>Erros comuns:</b> medir linhas de código ou horas trabalhadas; usar métricas de time para avaliar indivíduos (as pessoas passam a manipular os números); painel com 30 indicadores do qual não sai nenhuma decisão.</p>",
          k: ["Fluxo: lead time, cycle time, throughput, WIP, flow efficiency.",
              "<b>DORA:</b> frequência de deploy, lead time para mudanças, taxa de falha em mudanças, tempo de recuperação.",
              "<b>SPACE:</b> Satisfaction, Performance, Activity, Communication, Efficiency.",
              "Velocity serve para o time planejar, nunca para comparar times.",
              "Gráficos: burndown, CFD (diagrama de fluxo cumulativo), scatterplot de cycle time."] }
      ],
      pratica: "<p>Pegue um épico real e quebre em histórias que atendam INVEST. Priorize com RICE e WSJF e compare os resultados. Depois, defina 4 indicadores (2 de fluxo, 2 de resultado) para acompanhar o time.</p>",
      perguntas: [
        ["O que significa INVEST?", "Independent, Negotiable, Valuable, Estimable, Small, Testable."],
        ["Quais são as quatro métricas DORA?", "Frequência de deploy, lead time para mudanças, taxa de falha em mudanças e tempo de recuperação de falhas (MTTR)."],
        ["Por que não comparar velocity entre times?", "Porque story points são relativos a cada time; comparar incentiva inflar estimativas (Goodhart) e não diz nada sobre valor entregue."],
        ["Qual a diferença entre DEEP e INVEST?", "DEEP descreve o backlog como um todo (detalhado de forma adequada, estimado, emergente e priorizado); INVEST descreve cada história individualmente."],
        ["Como se calcula o WSJF?", "Cost of Delay (valor para o usuário/negócio + criticidade no tempo + redução de risco/habilitação de oportunidade) dividido pelo tamanho do trabalho. Maior WSJF, maior prioridade."],
        ["Pela Lei de Little, como reduzir o lead time sem aumentar a capacidade do time?", "Reduzindo o WIP: com o throughput constante, menos itens em andamento significam menos tempo médio de cada item no sistema."],
        ["Situação: o time puxa 12 itens por sprint, termina 5 e o resto fica \"quase pronto\". O que você investiga?", "Excesso de WIP e itens grandes demais. Ações: definir um Sprint Goal que foque o time, fatiar as histórias verticalmente, limitar o trabalho em andamento, olhar a idade dos itens e o CFD e mapear dependências externas que travam as entregas. Leve os dados para a retro."],
        ["Situação: a diretoria pede um ranking de produtividade dos times por story points. Como você responde?", "Story points são relativos a cada time e, como meta, seriam inflados (Goodhart). Proponha métricas de fluxo e DORA por time, junto com resultados de negócio e pesquisa com as pessoas (SPACE), usadas para melhorar o sistema e não para ranquear."]
      ],
      aprofundamento: [
        ["O Guia do Scrum 2020 (PDF em português)", "https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-PortugueseBR-3.0.pdf", "a definição oficial, em 13 páginas. Comece por aqui."],
        ["Kanban Guides — The Kanban Guide", "https://kanbanguides.org/", "guia oficial e aberto de Kanban, com PDF."],
        ["Kniberg — <i>Scrum and XP from the Trenches</i> (InfoQ)", "https://www.infoq.com/minibooks/scrum-xp-from-the-trenches-2/", "livro gratuito sobre Scrum na prática (requer cadastro no InfoQ)."],
        ["Retromat", "https://retromat.org/en/", "mais de 100 atividades de retrospectiva e gerador de planos."],
        ["Atlassian — Agile Coach", "https://www.atlassian.com/agile", "guias gratuitos de Scrum, Kanban, backlog, estimativas e métricas."],
        ["DORA — pesquisas e capacidades", "https://dora.dev/", "relatórios State of DevOps e guias das métricas de entrega."]
      ],
      referencias: [
        ["Manifesto Ágil (2001)", "https://agilemanifesto.org/iso/ptbr/manifesto.html"],
        ["Schwaber, K.; Sutherland, J. — Scrum Guide 2020", "https://scrumguides.org/"],
        ["Anderson, D. J. <i>Kanban</i> (2010) — Kanban University", "https://kanban.university/"],
        ["Patton, J. <i>User Story Mapping</i> (O'Reilly, 2014)", ""],
        ["Wake, B. \"INVEST in Good Stories\" (2003)", "https://xp123.com/invest-in-good-stories-and-smart-tasks/"],
        ["Intercom — RICE prioritization", "https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers/"],
        ["Reinertsen, D. <i>The Principles of Product Development Flow</i> (2009) — Cost of Delay e WSJF", ""],
        ["Scaled Agile — WSJF", "https://framework.scaledagile.com/wsjf"],
        ["Kerth, N. <i>Project Retrospectives</i> (2001) — Prime Directive", ""],
        ["Little, J. D. C. \"A Proof for the Queuing Formula: L = λW\" — Operations Research (1961)", ""],
        ["Vacanti, D. <i>Actionable Agile Metrics for Predictability</i> (2015)", ""],
        ["Forsgren, N.; Humble, J.; Kim, G. <i>Accelerate</i> (2018) e DORA", "https://dora.dev/"],
        ["Forsgren, N. et al. \"The SPACE of Developer Productivity\" — ACM Queue (2021)", "https://queue.acm.org/detail.cfm?id=3454124"]
      ]
    },
    {
      titulo: "Gestão Financeira e Sourcing",
      resumo: "O líder tech precisa falar a língua das finanças: orçar, prever, justificar investimentos e decidir o que fazer internamente, o que comprar e o que terceirizar.",
      topicos: [
        { t: "Estratégia de Sourcing",
          c: "<p>Decidir <b>make, buy ou partner</b> (construir, comprar ou fazer parceria). Construa o que é diferencial competitivo; compre ou terceirize o que é commodity.</p><p><b>Na prática:</b> no Wardley Map, cada componente evolui de <b>gênese</b> (novo, incerto) para <b>customizado</b>, depois <b>produto</b> e, por fim, <b>commodity</b> (serviço padronizado). Construir o que já é commodity desperdiça esforço; comprar o que está em gênese costuma ser impossível. Exemplo: autenticação de usuários é commodity, então se compra um provedor de identidade; um motor de precificação que é diferencial da empresa se constrói.</p><p>O <b>TCO</b> (custo total de propriedade) vai muito além da licença ou dos salários: infraestrutura, integração, treinamento, suporte, atualização, segurança e o custo de <b>sair</b> (migração de dados, novo contrato). Em contratos de alocação de pessoas (body shop), o risco da entrega fica com você; em contratos por escopo ou resultado, parte do risco passa ao fornecedor, que cobra por isso.</p><p><b>Erros comuns:</b> comparar só licença com salário; terceirizar o core e perder o conhecimento do negócio; ficar dependente de um fornecedor sem plano de saída.</p>",
          k: ["Modelos: insourcing, outsourcing, nearshore, offshore, body shop × entrega por escopo/resultado.",
              "Critérios: core × contexto, custo total (TCO), time-to-market, risco, lock-in, conhecimento retido.",
              "Wardley Maps ajudam a ver a evolução (gênese → customizado → produto → commodity)."] },
        { t: "RFP e LAP",
          c: "<p><b>RFP</b> (Request for Proposal) é o documento formal para pedir propostas a fornecedores; costuma vir depois de RFI (informação) e RFQ (cotação). No contexto do curso, <b>LAP</b> se refere ao processo de avaliação e aprovação de fornecedores/propostas — vale confirmar a definição exata no material da aula.</p><p><b>Exemplo de matriz ponderada:</b> peso 60% técnico e 40% comercial. No técnico: aderência aos requisitos (25), integração e APIs (15), segurança e LGPD (10), referências de clientes (10). No comercial: TCO em 3 anos (25), condições de saída (15). Cada avaliador dá nota de 1 a 5 separadamente, antes de discutir, para evitar que uma opinião forte contamine as outras.</p><p>No setor público, a <b>Lei 14.133/2021</b> (nova lei de licitações) exige um <b>estudo técnico preliminar</b>, que caracteriza a necessidade e a melhor solução, e um <b>termo de referência</b> antes da contratação. É um bom modelo mental também para empresas privadas: descreva o problema antes de escolher a solução.</p><p><b>Erros comuns:</b> RFP que descreve a solução de um fornecedor específico em vez do problema; decidir só pelo menor preço; contrato sem SLA mensurável e sem cláusula de saída.</p>",
          k: ["Uma boa RFP tem: contexto, escopo, requisitos funcionais e não funcionais, SLAs, critérios de avaliação e cronograma.",
              "Matriz de avaliação ponderada (técnica × comercial).",
              "Faça uma prova de conceito (PoC) antes de fechar contratos grandes.",
              "Contrato: SLAs, multas, cláusula de saída, propriedade intelectual, LGPD."] },
        { t: "Bimodal IT & Techquilibrium",
          c: "<p><b>Bimodal IT</b> (Gartner, 2014): Modo 1 = previsível, estável, foco em eficiência (sistemas legados); Modo 2 = exploratório, ágil, foco em inovação. Críticas: gerou TI de \"duas classes\". O Gartner evoluiu para o <b>Techquilibrium</b>: cada empresa encontra seu ponto de equilíbrio entre tradicional e digital, de acordo com seu setor e estratégia.</p><p><b>Na prática:</b> a principal crítica ao bimodal é que ele trata o legado como algo que não pode ser ágil. As pesquisas DORA (<i>Accelerate</i>) encontraram times de alto desempenho em todo tipo de sistema, inclusive mainframe: o que importa são as práticas (automação, testes, arquitetura com baixo acoplamento), e não a idade da tecnologia. Uma saída comum é aplicar a mesma engenharia a tudo e variar só o nível de controle conforme o risco de cada sistema.</p><p><b>Erros comuns:</b> tratar o time do legado como \"time de segunda\", o que afasta talentos; esquecer que os produtos digitais do \"modo 2\" dependem dos dados e das transações dos sistemas do \"modo 1\".</p>",
          k: ["Techquilibrium define níveis de ambição digital: de \"digitalizar operações\" a \"reinventar o modelo de negócio\".",
              "Ideia central: não é preciso ser 100% digital, e sim no ponto certo para competir."] },
        { t: "IT4IT Value Streams",
          c: "<p><b>IT4IT</b> é um padrão do The Open Group para gerir a TI como negócio. (A ementa escreve \"IT41T\", provavelmente um erro de digitação.) Na versão 2.1, que é a mais citada, ele organiza a TI em quatro fluxos de valor (lista abaixo).</p><p><b>Atualização:</b> a <b>versão 3.0</b> (2022) substituiu esses quatro por sete fluxos centrados no produto digital: <b>Evaluate</b> e <b>Explore</b> (que vieram do antigo Strategy to Portfolio), <b>Integrate</b>, <b>Deploy</b>, <b>Release</b>, <b>Consume</b> e <b>Operate</b>. Confira qual versão o material da aula usa.</p><p><b>Na prática:</b> o valor do IT4IT está em mostrar que a TI é uma cadeia ligada de ponta a ponta. Por exemplo, um incidente detectado em Detect to Correct deve voltar como item de backlog em Requirement to Deploy, e o custo de operação deve aparecer em Strategy to Portfolio na hora de decidir investimentos. Quando cada fluxo usa ferramentas e dados que não se conversam, a TI perde essa visão.</p><p><b>Erros comuns:</b> tratar o IT4IT como mais um processo burocrático; implantar ferramentas por fluxo sem integrar os dados entre elas.</p>",
          k: ["<b>Strategy to Portfolio (S2P):</b> estratégia e portfólio de investimentos.",
              "<b>Requirement to Deploy (R2D):</b> construir e entregar.",
              "<b>Request to Fulfill (R2F):</b> catálogo e atendimento de pedidos.",
              "<b>Detect to Correct (D2C):</b> operar, monitorar e corrigir.",
              "Liga-se a Value Stream Management e ao alinhamento de TI com o negócio."] },
        { t: "Budgeting, Forecast e Financial Plan",
          c: "<p><b>Budget</b> é o orçamento planejado (normalmente anual); <b>forecast</b> é a revisão periódica da previsão com base no realizado; <b>financial plan</b> é o plano de longo prazo.</p><p><b>Exemplo de business case:</b> investimento de R$ 500 mil que gera R$ 250 mil de benefício por ano durante 3 anos. ROI simples = (750 − 500) ÷ 500 = 50%. Payback = 2 anos. VPL a 12% ao ano ≈ 250 × (0,893 + 0,797 + 0,712) − 500 ≈ R$ 100 mil: positivo, então o projeto cria valor mesmo descontando o custo do dinheiro no tempo.</p><p>No Brasil, o <b>CPC 04 (R1)</b>, equivalente ao IAS 38, permite capitalizar gastos de <b>desenvolvimento</b> de software (virar ativo intangível e ser amortizado) quando certos critérios são atendidos, como viabilidade técnica e intenção de uso ou venda. Gastos de <b>pesquisa</b> vão para despesa. Por isso, o time de finanças pode pedir que as horas sejam registradas por projeto e por fase.</p><p><b>Showback</b> mostra a cada área quanto ela consome de TI; <b>chargeback</b> cobra de fato esse valor do orçamento dela.</p><p><b>Erros comuns:</b> business case só com benefícios otimistas e sem cenário pessimista; ignorar o custo do atraso (Cost of Delay); tratar o forecast como um novo orçamento, e não como informação para decidir.</p>",
          k: ["<b>CAPEX</b> (investimento, vira ativo e é depreciado/amortizado) × <b>OPEX</b> (despesa operacional). Cloud e SaaS deslocam gastos para OPEX.",
              "Rolling forecast: janela móvel de 12 a 18 meses.",
              "Business case: ROI, payback, VPL (NPV), TIR (IRR).",
              "Orçamento por produto/time em vez de por projeto (financiamento contínuo).",
              "Chargeback × showback de custos de TI."] }
      ],
      pratica: "<p>Monte um business case simples para migrar um sistema legado para SaaS: custos atuais (CAPEX e OPEX), custo do projeto, custo recorrente novo, benefícios, ROI e payback em 3 anos. Liste também os riscos de lock-in.</p>",
      perguntas: [
        ["Qual a diferença entre CAPEX e OPEX?", "CAPEX é investimento em ativos, contabilizado e depreciado ao longo do tempo; OPEX é despesa corrente de operação, reconhecida no período."],
        ["Quais os quatro value streams do IT4IT (versão 2.1)?", "Strategy to Portfolio, Requirement to Deploy, Request to Fulfill e Detect to Correct. Na versão 3.0 eles viraram sete: Evaluate, Explore, Integrate, Deploy, Release, Consume e Operate."],
        ["Quando faz sentido construir (make) em vez de comprar (buy)?", "Quando a capacidade é diferencial competitivo, não existe solução madura no mercado ou o custo e o risco de dependência de um fornecedor são altos."],
        ["O que entra no TCO além da licença?", "Infraestrutura, integração, treinamento, suporte, atualizações, segurança, pessoas para operar e o custo de sair (migração e novo contrato)."],
        ["Quais os estágios de evolução de um componente no Wardley Map?", "Gênese, customizado, produto e commodity (ou utility)."],
        ["Qual a diferença entre showback e chargeback?", "Showback mostra às áreas quanto elas consomem de TI; chargeback cobra esse valor do orçamento delas."],
        ["Um projeto custa R$ 500 mil e gera R$ 250 mil por ano por 3 anos. Qual o payback e o ROI simples?", "Payback de 2 anos e ROI simples de 50% ((750 − 500) ÷ 500). O VPL, a 12% ao ano, fica em torno de R$ 100 mil."],
        ["Situação: o CFO pede um corte de 20% no orçamento de TI. Como você responde?", "Traga o custo por produto ou serviço (showback) e classifique cada gasto: core, commodity ou desperdício (licenças ociosas, recursos de cloud sem uso). Proponha os cortes com o impacto e o risco de cada um e mostre o que não deve ser cortado porque gera receita ou reduz risco. Deixe a decisão final explícita, com os trade-offs."]
      ],
      aprofundamento: [
        ["OpenStax — <i>Principles of Managerial Accounting</i>, cap. 7 (Budgeting)", "https://openstax.org/books/principles-managerial-accounting/pages/7-1-describe-how-and-why-managers-use-budgets", "livro-texto aberto: orçamento mestre, flexível, base zero. Comece por aqui."],
        ["OpenStax — <i>Principles of Finance</i>", "https://openstax.org/details/books/principles-finance", "livro aberto: valor do dinheiro no tempo, VPL, TIR e orçamento de capital."],
        ["Simon Wardley — <i>Wardley Maps</i> (livro gratuito)", "https://learnwardleymapping.com/book/", "o livro completo sobre mapas de estratégia, útil para decidir construir × comprar."],
        ["The Open Group — IT4IT", "https://www.opengroup.org/it4it", "página oficial do padrão (o download requer cadastro gratuito)."]
      ],
      referencias: [
        ["The Open Group — IT4IT Reference Architecture", "https://www.opengroup.org/it4it"],
        ["Gartner — Bimodal (glossário)", "https://www.gartner.com/en/information-technology/glossary/bimodal"],
        ["Gartner — \"Techquilibrium\" (Symposium/ITxpo 2018)", "https://www.gartner.com/en/newsroom"],
        ["Wardley, S. — Wardley Maps (livro aberto)", "https://learnwardleymapping.com/"],
        ["Kersten, M. <i>Project to Product</i> (2018) — Flow Framework", "https://flowframework.org/"],
        ["Hope, J.; Fraser, R. <i>Beyond Budgeting</i> (2003) — BBRT", "https://bbrt.org/"],
        ["Reinertsen, D. <i>The Principles of Product Development Flow</i> — Cost of Delay/WSJF", ""],
        ["The Open Group — IT4IT Standard, Version 3.0 (value streams)", "https://pubs.opengroup.org/it4it/3.0/snapshot/VSs_IT4IT-Value-Streams.html"],
        ["Lei 14.133/2021 — Licitações e Contratos Administrativos (Planalto)", "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm"],
        ["CPC 04 (R1) — Ativo Intangível (equivalente ao IAS 38)", ""],
        ["Forsgren, N.; Humble, J.; Kim, G. <i>Accelerate</i> (2018)", ""]
      ]
    },
    {
      titulo: "Comunicação e Negociação em Projetos de TI",
      resumo: "Grande parte do trabalho do líder é conversa: negociar prazos e escopo, mediar conflitos e apresentar ideias de forma convincente.",
      topicos: [
        { t: "Estilos de negociação",
          c: "<p>O método de Harvard (<i>Como Chegar ao Sim</i>): separe as <b>pessoas</b> do problema, foque em <b>interesses</b> e não em posições, crie <b>opções</b> de ganho mútuo e use <b>critérios objetivos</b>. Conheça sua <b>BATNA</b> (a melhor alternativa se não houver acordo).</p><p><b>Exemplo:</b> a diretoria exige o novo app até 1º de março (a <b>posição</b>). Perguntando o porquê, você descobre que o <b>interesse</b> é ter algo para mostrar num evento com clientes nessa data. As <b>opções</b> se abrem: uma versão com as três funções que aparecem na demonstração, um protótipo navegável para o evento, ou lançar só para clientes piloto. O critério objetivo é o histórico de throughput do time, que mostra o que cabe até lá.</p><p>Numa negociação com fornecedor, sua BATNA pode ser outro fornecedor já avaliado ou manter a solução atual por mais um ano. Quanto melhor ela for, menos você precisa aceitar. A <b>ZOPA</b> existe quando o máximo que você aceita pagar é maior que o mínimo que o fornecedor aceita receber.</p><p><b>Erros comuns:</b> dividir a diferença cedo demais, antes de explorar interesses; negociar sem ter definido a própria BATNA; aceitar prazo e escopo fixos ao mesmo tempo e pagar a conta com a qualidade.</p>",
          k: ["Negociação distributiva (dividir um bolo fixo) × integrativa (aumentar o bolo).",
              "ZOPA: zona de possível acordo.",
              "Ancoragem: quem faz a primeira oferta influencia o resultado.",
              "Em TI: negocie escopo e qualidade de forma explícita — prazo fixo pede escopo flexível."] },
        { t: "Gestão de conflitos",
          c: "<p>O modelo <b>Thomas-Kilmann</b> mapeia cinco estilos com base em assertividade × cooperação: <b>competir</b>, <b>colaborar</b>, <b>comprometer-se (ceder parte)</b>, <b>evitar</b> e <b>acomodar</b>.</p><p><b>Quando usar cada um:</b> <b>competir</b> em decisões urgentes ou de segurança; <b>colaborar</b> quando o assunto é importante para os dois lados e há tempo; <b>ceder parte</b> quando os objetivos são moderadamente importantes e é preciso fechar; <b>evitar</b> quando o assunto é trivial ou os ânimos precisam esfriar; <b>acomodar</b> quando o assunto importa mais para o outro lado ou você percebe que estava errado. O problema é usar sempre o mesmo estilo.</p><p><b>O que diz a pesquisa:</b> Jehn (1995) encontrou benefícios do conflito de tarefa. A meta-análise de De Dreu e Weingart (2003) achou, em média, efeito negativo dos dois tipos. Revisões posteriores (de Wit, Greer e Jehn, 2012) indicam que o conflito de tarefa ajuda quando não se mistura com o pessoal e quando há confiança no time. O \"disagree and commit\" é um dos princípios de liderança da Amazon (\"Have Backbone; Disagree and Commit\").</p><p><b>Erros comuns:</b> resolver o conflito de duas pessoas em público ou por intermediários; deixar crescer esperando que se resolva sozinho; tratar discordância técnica como ataque pessoal.</p>",
          k: ["Conflito de tarefa (ideias) pode ser saudável; conflito de relacionamento (pessoal) é destrutivo.",
              "Traga o conflito cedo, em particular, com fatos.",
              "Disagree and commit: discorde, mas se comprometa depois da decisão."] },
        { t: "Escuta ativa",
          c: "<p>Ouvir para entender, não para responder. Técnicas: parafrasear, fazer perguntas abertas, resumir, validar emoções, tolerar silêncios.</p><p><b>Exemplo em um 1:1:</b> a pessoa diz \"esse projeto é uma bagunça\". A reação automática é defender o projeto ou dar uma solução. A escuta ativa pergunta \"o que está parecendo bagunça pra você?\", ouve, e resume: \"então o problema maior é que as prioridades mudam toda semana e você perde o que já tinha feito, é isso?\". Só depois, se fizer sentido, vem a pergunta \"o que ajudaria?\".</p><p>Rogers e Farson descrevem a escuta ativa como ouvir o <b>sentido total</b>: o conteúdo e o sentimento por trás dele. Muitas vezes a pessoa não quer uma solução imediata, e sim ser entendida antes.</p><p><b>Erros comuns:</b> pular direto para o conselho; fingir que escuta enquanto olha o celular; transformar o assunto do outro numa história sua (\"comigo aconteceu pior…\").</p>",
          k: ["\"Deixa eu ver se entendi: você está dizendo que…\"",
              "Evite interromper e preparar a resposta enquanto o outro fala.",
              "Perguntas abertas: como, o que, o que mais…"] },
        { t: "Comunicação assertiva e passiva",
          c: "<p>Quatro estilos: <b>passivo</b> (não expressa as próprias necessidades), <b>agressivo</b> (impõe, desrespeita), <b>passivo-agressivo</b> (indireto, sarcástico) e <b>assertivo</b> (claro, direto e respeitoso).</p><p><b>Roteiro DESC</b> (Bower e Bower): <b>Descrever</b> o fato, <b>Expressar</b> o efeito, <b>Especificar</b> o que você pede, <b>Consequências</b> positivas do acordo. Exemplo para um stakeholder que pede urgências direto aos devs: \"Nas últimas duas semanas, chegaram cinco pedidos direto no chat dos devs (D). Isso interrompe a sprint e atrasa o que você mesmo priorizou (E). Pode mandar os pedidos para mim ou para o PO? (S) Assim, a gente avalia no mesmo dia e você recebe um prazo real (C).\"</p><p>O mesmo comportamento soa diferente em cada estilo. Passivo: aceitar a tarefa extra e ficar até tarde. Agressivo: \"isso não é problema meu\". Passivo-agressivo: aceitar e atrasar de propósito. Assertivo: \"consigo fazer, mas algo sai da semana; o que você prefere adiar?\".</p><p><b>Erros comuns:</b> confundir assertividade com agressividade e, por medo, ficar no passivo; dizer não sem oferecer alternativa.</p>",
          k: ["Assertividade: \"Eu entendo X, e preciso de Y porque Z.\"",
              "Saber dizer não com alternativa: \"Não consigo até sexta; consigo entregar A na sexta e B na terça.\""] },
        { t: "Comunicação não-violenta",
          c: "<p>Método de Marshall Rosenberg em quatro passos: <b>Observação</b> (fato sem julgamento) → <b>Sentimento</b> → <b>Necessidade</b> → <b>Pedido</b> (concreto e negociável).</p><p><b>Sentimento × julgamento disfarçado:</b> \"sinto que você não se importa com o time\" não é sentimento, é uma avaliação sobre o outro. Sentimentos são estados seus: preocupado, frustrado, aliviado, inseguro. Rosenberg também diferencia <b>pedido</b> de <b>exigência</b>: se um \"não\" gera punição, era uma exigência.</p><p>A CNV também serve para <b>ouvir</b>: diante de uma crítica dura, tente identificar a necessidade por trás dela. \"Esse sistema nunca funciona!\" pode significar \"preciso conseguir fechar o mês sem depender de ajuda\".</p><p><b>Erros comuns:</b> usar os quatro passos como fórmula robótica; usar a CNV para manipular (\"eu preciso que você faça hora extra\"); pular a observação e começar pelo pedido.</p>",
          k: ["Ex.: \"Nas duas últimas dailies você chegou 15 min depois (observação). Fico preocupado (sentimento) porque preciso que o time esteja alinhado (necessidade). Podemos ajustar o horário ou você consegue chegar no início? (pedido)\"",
              "Julgamentos (\"você é desorganizado\") geram defesa; observações abrem diálogo."] },
        { t: "Pitch e apresentação",
          c: "<p>Estruture para a audiência. Para executivos, use o <b>Princípio da Pirâmide</b> (Barbara Minto): comece pela conclusão, depois os argumentos, depois os detalhes. Método <b>SCQA</b>: Situação, Complicação, Questão, Resposta.</p><p><b>Exemplo de SCQA para pedir tempo para dívida técnica:</b> <b>Situação:</b> o checkout processa 40% da receita. <b>Complicação:</b> tivemos três incidentes no trimestre, e cada mudança leva duas semanas por causa do acoplamento. <b>Questão:</b> como reduzir esse risco sem parar o roadmap? <b>Resposta:</b> dedicar 20% da capacidade do time por dois trimestres para separar o módulo de pagamentos, com a meta de voltar a fazer deploy diário e reduzir os incidentes pela metade. Em seguida, o pedido: aprovar essa alocação hoje.</p><p>Na pirâmide de Minto, a resposta vem primeiro porque executivos têm pouco tempo: se pararem de ler no primeiro parágrafo, já sabem o que você propõe.</p><p><b>Erros comuns:</b> começar pelo histórico técnico e só chegar ao pedido no último slide; slides cheios de texto lido em voz alta; falar de tecnologia para quem decide com base em risco, custo e receita.</p>",
          k: ["Elevator pitch em 30–60 segundos: problema, solução, diferencial, pedido.",
              "Um slide = uma ideia.",
              "Traga números e uma história concreta.",
              "Termine com um pedido claro (decisão, orçamento, apoio)."] }
      ],
      pratica: "<p>Reescreva em formato CNV um feedback difícil que você precisa dar. Depois, prepare um pitch de 3 minutos com SCQA para pedir orçamento para pagar dívida técnica.</p>",
      perguntas: [
        ["O que é BATNA?", "Best Alternative To a Negotiated Agreement — a melhor alternativa caso a negociação não dê certo; define seu poder de negociação."],
        ["Quais os quatro componentes da CNV?", "Observação, sentimento, necessidade e pedido."],
        ["O que é o Princípio da Pirâmide?", "Começar pela resposta/conclusão principal e depois apresentar os argumentos que a sustentam, em grupos lógicos."],
        ["Qual a diferença entre posição e interesse numa negociação?", "Posição é o que a pessoa pede (\"o app até março\"); interesse é o motivo por trás do pedido (\"ter algo para mostrar no evento\"). Negociar interesses abre opções que as posições escondem."],
        ["O que é ZOPA?", "A zona de possível acordo: o intervalo em que o limite de uma parte se sobrepõe ao da outra. Se não há sobreposição, não há acordo possível nessas condições."],
        ["Quais os passos do roteiro DESC?", "Descrever o fato, Expressar o efeito, Especificar o pedido e mostrar as Consequências positivas."],
        ["Por que \"sinto que você não se importa\" não é um sentimento na CNV?", "Porque é um julgamento sobre o outro disfarçado de sentimento. Um sentimento descreve o próprio estado, como preocupação ou frustração."],
        ["Situação: um diretor exige uma data que o time considera impossível. Como você conduz?", "Descubra o interesse por trás da data, mostre com dados (throughput histórico) o que cabe até lá e ofereça opções: escopo reduzido, entrega em fases, piloto. Deixe explícito o que acontece com a qualidade se escopo e prazo ficarem fixos, e registre a decisão."]
      ],
      aprofundamento: [
        ["Coursera — Successful Negotiation (University of Michigan)", "https://www.coursera.org/learn/negotiation-skills", "curso gratuito no modo ouvinte (audit), com as 4 etapas da negociação. Comece por aqui."],
        ["PUCRS Online — Comunicação não violenta, empatia e cooperação", "https://online.pucrs.br/formacao-gratuita/comunicacao-nao-violenta-empatia-e-cooperacao", "curso gratuito em português."],
        ["MIT OpenCourseWare — Advanced Communication for Leaders", "https://ocw.mit.edu/courses/15-281-advanced-communication-for-leaders-spring-2016/", "reuniões, escuta ativa, apresentar para públicos difíceis."],
        ["Harvard Program on Negotiation — blog", "https://www.pon.harvard.edu/blog/", "artigos gratuitos sobre negociação e conflitos."]
      ],
      referencias: [
        ["Fisher, R.; Ury, W. <i>Como Chegar ao Sim</i> (1981) — Harvard Program on Negotiation", "https://www.pon.harvard.edu/"],
        ["Thomas, K.; Kilmann, R. — Thomas-Kilmann Conflict Mode Instrument", "https://kilmanndiagnostics.com/overview-thomas-kilmann-conflict-mode-instrument-tki/"],
        ["Rosenberg, M. <i>Comunicação Não-Violenta</i> — Center for Nonviolent Communication", "https://www.cnvc.org/"],
        ["Patterson, K. et al. <i>Conversas Cruciais</i> (2002)", ""],
        ["Minto, B. <i>O Princípio da Pirâmide</i> (1987) — inclui SCQA", "https://www.barbaraminto.com/"],
        ["Rogers, C.; Farson, R. \"Active Listening\" (1957)", ""],
        ["Bower, S.; Bower, G. <i>Asserting Yourself</i> (1976) — roteiro DESC", ""],
        ["Jehn, K. \"A Multimethod Examination of the Benefits and Detriments of Intragroup Conflict\" — Administrative Science Quarterly (1995)", ""],
        ["De Dreu, C.; Weingart, L. \"Task Versus Relationship Conflict, Team Performance, and Team Member Satisfaction: A Meta-Analysis\" — Journal of Applied Psychology (2003)", ""],
        ["de Wit, F.; Greer, L.; Jehn, K. \"The Paradox of Intragroup Conflict: A Meta-Analysis\" — Journal of Applied Psychology (2012)", ""],
        ["Amazon — Leadership Principles (\"Have Backbone; Disagree and Commit\")", "https://www.amazon.jobs/content/en/our-workplace/leadership-principles"]
      ]
    }
  ],
  challenge: {
    intro: "Sugestão de projeto: evolua o produto da Fase 1 definindo como a organização vai entregá-lo.",
    entregas: ["Topologia de times (squads/tribos ou Team Topologies) com justificativa.", "Rituais ágeis, Definition of Done e indicadores de acompanhamento.", "Estratégia de sourcing (o que construir × comprar) e uma RFP resumida.", "Orçamento de 12 meses com CAPEX/OPEX e business case.", "Plano de comunicação com stakeholders."]
  }
});
